// data.js — PolicyReady.org shared product data
// Used by shop.html, state.html, and manual.html

const STATES = [
  {
    id: "co",
    name: "Colorado",
    program: "Host Home Program",
    agency: "HCPF",
    citation: "10 CCR 2505-10",
    manuals: [
      {
        id: "co-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Host Home Provider",
        file: "CO_Individual_Provider_JC_FINAL.docx",
        pages: 71,
        slug: "co-individual",
        summary: "Built for individuals and families becoming a Colorado Host Home Provider under the HCPF-administered waiver system.",
        details: "This manual walks through the Colorado-specific terminology you'll actually need — your PASA, your CCB, the CBI background check process, and QMAP medication certification. Every policy reflects 10 CCR 2505-10 and the HCBS Settings Final Rule, including the full person-centered planning process tied to your PCP/ISP.",
        bullets: [
          "Colorado HCPF, PASA, and CCB terminology throughout",
          "CBI background check process and QMAP certification guidance",
          "PCP/ISP implementation and HCBS settings compliance",
          "Relief coverage, planned absence, and emergency coverage procedures",
          "Home environment and physical safety standards specific to Colorado",
        ],
      },
      {
        id: "co-agency",
        edition: "Agency Edition",
        title: "Policy & Procedure Manual for Host Home Provider Agency",
        file: "CO_Agency_PASA_JC_FINAL.docx",
        pages: 69,
        slug: "co-agency",
        summary: "Built for PASAs and organizations overseeing multiple Colorado Host Home placements.",
        details: "Covers the agency side of Colorado's Host Home program — staff qualifications, CBI background clearance tracking, host home provider contracting and vetting, on-call coordinator systems, and ongoing monitoring obligations under your PASA designation.",
        bullets: [
          "PASA/CCB agency structure and oversight responsibilities",
          "Host home provider contracting and vetting procedures",
          "On-call coordinator and 24-hour coverage protocols",
          "Staff personnel files and CBI background check tracking",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
  {
    id: "az",
    name: "Arizona",
    program: "Developmental Home Program",
    agency: "DES/DDD",
    citation: "A.A.C. R6-6-1101",
    manuals: [
      {
        id: "az-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Developmental Home Provider",
        file: "AZ_Individual_Provider_JC_FINAL.docx",
        pages: 71,
        slug: "az-individual",
        summary: "Built for individuals becoming an Arizona Developmental Home Provider under DES/DDD.",
        details: "Covers the Arizona DPS Fingerprint Clearance Card process, your Qualified Vendor relationship, ISP implementation, and the Life Safety Inspection required every two years. Every policy aligns with A.A.C. R6-6-1101 and OLCR oversight requirements.",
        bullets: [
          "Arizona DPS Fingerprint Clearance Card requirements",
          "Qualified Vendor relationship and ISP implementation",
          "Life Safety Inspection (every 2 years) and OLCR compliance",
          "DDD-approved medication administration training",
          "Article 9 behavioral support documentation",
        ],
      },
      {
        id: "az-agency",
        edition: "Qualified Vendor Agency",
        title: "Policy & Procedure Manual for Developmental Home Provider Agency",
        file: "AZ_Agency_QualifiedVendor_JC_FINAL.docx",
        pages: 69,
        slug: "az-agency",
        summary: "Built for Qualified Vendor agencies overseeing Arizona Developmental Homes.",
        details: "Covers Qualified Vendor certification and DDD oversight, developmental home provider contracting and Life Safety Inspection coordination, and the Arizona DPS clearance tracking required for every household member.",
        bullets: [
          "Qualified Vendor agency structure and DDD oversight",
          "Developmental home contracting and ongoing monitoring",
          "Arizona DPS background check and training requirements",
          "On-call coordinator and emergency coverage systems",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
  {
    id: "fl",
    name: "Florida",
    program: "Foster Care Facility",
    agency: "APD",
    citation: "65G-2 F.A.C.",
    manuals: [
      {
        id: "fl-individual",
        edition: "Individual Operator",
        title: "Policy & Procedure Manual for Foster Care Facility Operator",
        file: "FL_Individual_Operator_JC_FINAL.docx",
        pages: 70,
        slug: "fl-individual",
        summary: "Built for individuals becoming a Florida Foster Care Facility Operator under APD.",
        details: "Covers the Level II background screening process through the AHCA Clearinghouse, your relationship with your MWSO, and the specific 65G-7 medication and 65G-8 behavioral support requirements that govern Florida's iBudget Waiver setting.",
        bullets: [
          "Level II background screening via AHCA Clearinghouse (§393.0655)",
          "APD, MWSO, and iBudget Waiver terminology throughout",
          "65G-7 medication management and 65G-8 reactive strategies",
          "APD monthly monitoring visit compliance",
          "Support Plan implementation and documentation standards",
        ],
      },
      {
        id: "fl-agency",
        edition: "Licensed Provider Agency",
        title: "Policy & Procedure Manual for Foster Care Facility Agency",
        file: "FL_Agency_LicensedProvider_JC_FINAL.docx",
        pages: 68,
        slug: "fl-agency",
        summary: "Built for APD-licensed agencies overseeing multiple Florida Foster Care Facilities.",
        details: "Covers agency-level AHCA Clearinghouse screening management, staff credentialing, APD licensing compliance, and the structure required to support multiple foster care facility operators under one organization.",
        bullets: [
          "APD licensed provider agency structure and oversight",
          "AHCA Clearinghouse process and staff credentialing",
          "APD monthly monitoring visit requirements",
          "Provider vetting, contracting, and ongoing supervision",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
  {
    id: "tx",
    name: "Texas",
    program: "Host Home/Companion Care",
    agency: "HHSC",
    citation: "26 TAC Ch. 263",
    manuals: [
      {
        id: "tx-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Host Home/Companion Care Provider",
        file: "TX_Individual_HH_CC_Provider_JC_FINAL.docx",
        pages: 71,
        slug: "tx-individual",
        summary: "Built for individuals becoming a Texas HCS Host Home/Companion Care Provider under HHSC.",
        details: "Walks through Texas's three-part TULIP background clearance — DPS criminal history, the Employee Misconduct Registry, and the Nurse Aide Registry — plus your relationship with your Program Provider and LIDDA Service Coordinator, and the IPC/Implementation Plan structure unique to Texas.",
        bullets: [
          "TULIP three-part clearance: DPS criminal history, EMR, NAR",
          "Annual EMR and NAR re-verification requirements",
          "HHSC, LIDDA, Program Provider, IPC/IP terminology",
          "Substitute Caregiver background clearance and orientation",
          "26 TAC Ch. 263 and HCS Program Handbook compliance",
        ],
      },
      {
        id: "tx-agency",
        edition: "HCS Program Provider",
        title: "Policy & Procedure Manual for HCS Program Provider",
        file: "TX_Program_Provider_JC_FINAL.docx",
        pages: 68,
        slug: "tx-agency",
        summary: "Built for HHSC-contracted Program Providers overseeing multiple Texas HH/CC placements.",
        details: "Covers Program Provider contract obligations, TULIP background check oversight for every provider and household member, HH/CC provider vetting and home certification, and the site-specific Medicaid coordination required through HHSC.",
        bullets: [
          "HHSC Program Provider contract and TULIP oversight",
          "HH/CC provider vetting, contracting, and home certification",
          "IPC/Implementation Plan management procedures",
          "On-call coordinator and substitute caregiver coordination",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
  {
    id: "nm",
    name: "New Mexico",
    program: "Family Living",
    agency: "DDSD / HCA",
    citation: "8.314.5 NMAC",
    manuals: [
      {
        id: "nm-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Family Living Provider",
        file: "NM_Individual_FamilyLiving_Provider_JC_FINAL.docx",
        pages: 73,
        slug: "nm-individual",
        summary: "Built for individuals becoming a New Mexico DDW Family Living Provider under DDSD.",
        details: "Walks through New Mexico's two-step background clearance — the COR/EAR check that must clear before care begins, and the CCHSP fingerprint check due within twenty calendar days — along with the two-person capacity limit, Therap documentation requirements, and the water temperature standard from DDW Numbered Memo 2025-03.",
        bullets: [
          "COR/EAR check before care begins, CCHSP within 20 days",
          "Two-person capacity limit under 8.314.5 NMAC",
          "Therap documentation requirements per DDSD",
          "Water temperature standard (DDW Numbered Memo 2025-03)",
          "PRN medication clarification per DDW Numbered Memo 2024-03",
        ],
      },
      {
        id: "nm-agency",
        edition: "DDW Provider Agency",
        title: "Policy & Procedure Manual for DDW Family Living Provider Agency",
        file: "NM_Provider_Agency_JC_FINAL.docx",
        pages: 70,
        slug: "nm-agency",
        summary: "Built for DDSD-contracted Provider Agencies overseeing multiple New Mexico Family Living homes.",
        details: "Covers agency-level COR/EAR and CCHSP clearance tracking, home study procedures, capacity limit compliance across all placements, Therap documentation oversight, and the DHI monitoring relationship required under DDW Service Standards.",
        bullets: [
          "DDSD Provider Agency contract and DHI oversight",
          "Family Living provider vetting and home study procedures",
          "Annual COR/EAR re-clearance tracking across all providers",
          "Therap documentation oversight and PRN medication compliance",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
  {
    id: "ga",
    name: "Georgia",
    program: "Host Home / Life-Sharing",
    agency: "DBHDD",
    citation: "DBHDD Policy 02-704",
    manuals: [
      {
        id: "ga-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Host Home/Life-Sharing Provider",
        file: "GA_Individual_HostHome_Provider_JC_FINAL.docx",
        pages: 68,
        slug: "ga-individual",
        summary: "Built for individuals becoming a Georgia Host Home/Life-Sharing Provider under DBHDD.",
        details: "Covers the GCHEXS fingerprint background check process through IdentoGo, your relationship with your CRA Provider Agency and the Georgia Collaborative ASO, and the NOW/COMP Waiver terminology and capacity limits specific to Georgia's CRA services.",
        bullets: [
          "GCHEXS (IdentoGo) fingerprint background check process",
          "DBHDD, NOW/COMP Waiver, CRA, Georgia Collaborative ASO",
          "Two-person capacity limit per DBHDD Policy 02-704",
          "DDP role, Support Coordinator, and ISP enrollment procedures",
          "Relief caregiver background clearance and orientation",
        ],
      },
      {
        id: "ga-agency",
        edition: "CRA Provider Agency",
        title: "Policy & Procedure Manual for CRA Provider Agency",
        file: "GA_Agency_CRA_Provider_JC_FINAL.docx",
        pages: 67,
        slug: "ga-agency",
        summary: "Built for DBHDD-contracted CRA Provider Agencies overseeing multiple Georgia Host Homes.",
        details: "Covers DBHDD CRA agency certification, the Georgia Collaborative ASO enrollment process, the site-specific Medicaid provider number procedure required for every host home, and DDP attestation requirements under DBHDD oversight.",
        bullets: [
          "DBHDD CRA agency certification and ASO enrollment",
          "Site-specific Medicaid provider number process",
          "DDP attestation and GCHEXS oversight for all providers",
          "Host home vetting, contracting, and monitoring visits",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
  {
    id: "ca",
    name: "California",
    program: "Family Home Agency (FHA)",
    agency: "DDS / Regional Center",
    citation: "Title 17 CCR §56075",
    manuals: [
      {
        id: "ca-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Family Home Provider (FHA)",
        file: "CA_Individual_FamilyHome_Provider_JC_FINAL.docx",
        pages: 70,
        slug: "ca-individual",
        summary: "Built for individuals becoming a California Family Home Provider under an FHA.",
        details: "Covers the DOJ LiveScan background check process through California's CBCB, the FHA and Regional Center relationship structure, and the IPP and consumer terminology used throughout California's DDS system — plus the additional privacy protections required under California's CMIA.",
        bullets: [
          "DOJ LiveScan background check (California CBCB)",
          "FHA, Regional Center, IPP, and consumer terminology",
          "HIPAA plus California CMIA privacy compliance",
          "FHA home study and ongoing monitoring requirements",
          "Relief caregiver background clearance and orientation",
        ],
      },
      {
        id: "ca-agency",
        edition: "Family Home Agency (FHA)",
        title: "Policy & Procedure Manual for Family Home Agency (FHA)",
        file: "CA_FamilyHomeAgency_JC_FINAL.docx",
        pages: 69,
        slug: "ca-agency",
        summary: "Built for Family Home Agencies vendored by a California Regional Center.",
        details: "Covers FHA vendorization through one of California's 21 Regional Centers, Title 17 CCR §56095 monitoring requirements, §56083 social service staff qualifications, and the DOJ LiveScan oversight required for every family home provider and household member.",
        bullets: [
          "FHA vendorization through a California Regional Center",
          "Title 17 CCR §56095 monitoring and §56083 staff qualifications",
          "FHA home study and DOJ LiveScan oversight",
          "Family home provider vetting and ongoing supervision",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
  {
    id: "oh",
    name: "Ohio",
    program: "Ohio Shared Living",
    agency: "DODD",
    citation: "OAC 5123-9-33",
    manuals: [
      {
        id: "oh-individual",
        edition: "Independent Provider",
        title: "Policy & Procedure Manual for Shared Living Independent Provider",
        file: "OH_Individual_SharedLiving_Provider_JC_FINAL.docx",
        pages: 70,
        slug: "oh-individual",
        summary: "Built for individuals becoming an Ohio DODD Shared Living Independent Provider.",
        details: "Covers Ohio's BCI and FBI fingerprint clearance process, the DODD Abuse Registry check, your relationship with your County Board SSA, and the Medication Administration Certification and nurse delegation requirements specific to non-related caregivers under OAC 5123-9-33.",
        bullets: [
          "BCI + FBI fingerprint clearance and DODD Abuse Registry check",
          "DODD, SSA, County Board of DD, ISP terminology",
          "MUI/UI incident reporting (Ohio-specific terms)",
          "Medication Administration Certification and nurse delegation",
          "Four-person capacity limit and primary residence requirement",
        ],
      },
      {
        id: "oh-agency",
        edition: "Agency Provider",
        title: "Policy & Procedure Manual for Shared Living Agency Provider",
        file: "OH_Agency_SharedLiving_Provider_JC_FINAL.docx",
        pages: 69,
        slug: "oh-agency",
        summary: "Built for DODD-certified Agency Providers overseeing multiple Ohio Shared Living caregivers.",
        details: "Covers DODD Agency Provider certification through the PSM system, Director of Operations and QIDP qualifications, shared living caregiver contracting and primary residence verification, and the monthly UI Log review process required under DODD policy.",
        bullets: [
          "DODD Agency Provider certification (OAC 5123-2-08) via PSM",
          "Director of Operations and QIDP qualifications",
          "Shared living caregiver contracting and monitoring",
          "Monthly UI Log review and MUI reporting requirements",
          "Quality management and corrective action procedures",
        ],
      },
    ],
  },
];

// Flat lookup for manual.html
function findManual(slug) {
  for (const state of STATES) {
    const m = state.manuals.find((m) => m.slug === slug);
    if (m) return { ...m, state };
  }
  return null;
}

// Flat lookup for state.html
function findState(id) {
  return STATES.find((s) => s.id === id) || null;
}
