// data.js — PolicyReady.org shared product data
// Used by shop.html, state.html, and manual.html
//
// NOTE: Manuals now carry their own regulatory context (agency, citation, pages,
// policies, category) because a state can have several programs (host home,
// behavioral health, etc.). The state-level program/agency/citation is used only
// for the shop card and state header; each manual's detail page uses its own.

const STATES = [
  {
    id: "co",
    name: "Colorado",
    program: "Host Home Program",
    agency: "HCPF",
    citation: "10 CCR 2505-10",
    manuals: [
      {
        id: "co-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Host Home Provider",
        file: "CO_Individual_Provider_JC_FINAL.docx",
        pages: 71,
        slug: "co-individual",
        summary: "Built for individuals and families becoming a Colorado Host Home Provider under the HCPF-administered waiver system.",
        details: "This manual walks through the Colorado-specific terminology you'll actually need — your PASA, your CCB, the CBI background check process, and QMAP medication certification. Every policy reflects 10 CCR 2505-10 and the HCBS Settings Final Rule, including the full person-centered planning process tied to your PCP/ISP.",
        bullets: [
          "Colorado HCPF, PASA, and CCB terminology throughout",
          "CBI background check process and QMAP certification guidance",
          "PCP/ISP implementation and HCBS settings compliance",
          "Relief coverage, planned absence, and emergency coverage procedures",
          "Home environment and physical safety standards specific to Colorado",
        ],
      },
      {
        id: "co-agency",
        edition: "Agency Edition",
        title: "Policy & Procedure Manual for Host Home Provider Agency",
        file: "CO_Agency_PASA_JC_FINAL.docx",
        pages: 69,
        slug: "co-agency",
        summary: "Built for PASAs and organizations overseeing multiple Colorado Host Home placements.",
        details: "Covers the agency side of Colorado's Host Home program — staff qualifications, CBI background clearance tracking, host home provider contracting and vetting, on-call coordinator systems, and ongoing monitoring obligations under your PASA designation.",
        bullets: [
          "PASA/CCB agency structure and oversight responsibilities",
          "Host home provider contracting and vetting procedures",
          "On-call coordinator and 24-hour coverage protocols",
          "Staff personnel files and CBI background check tracking",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "co-bhe",
        edition: "Behavioral Health Entity — Base",
        category: "Behavioral Health — Integrated",
        title: "Behavioral Health Entity (BHE) Base Policy & Procedure Manual",
        file: "CO Behavioral Health Entity (BHE) Base PP Manual.docx",
        pages: 87,
        slug: "co-bhe",
        agency: "Colorado BHA",
        citation: "2 CCR 502-1",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "The core manual for a Colorado Behavioral Health Entity (BHE) licensed by the Behavioral Health Administration — covering both mental health and substance use under one integrated license.",
        details: "Built to the BHA's Behavioral Health Entity rule (2 CCR 502-1), this base manual establishes governance, personnel and background checks, client rights and grievances, records and confidentiality, screening and assessment, service planning, safety, and quality management for a BHE. Add the endorsement modules below for the specific services you deliver.",
        bullets: [
          "Colorado BHA Behavioral Health Entity (BHE) licensing framework",
          "Integrated mental health and substance use under one license",
          "Client rights, grievances, records, and confidentiality (including 42 CFR Part 2 where applicable)",
          "Screening, assessment, and person-centered service planning",
          "Governance, personnel, background checks, and quality management",
        ],
      },
      {
        id: "co-bhe-outpatient-addon",
        edition: "Outpatient Endorsement",
        category: "Behavioral Health — Endorsement",
        title: "BHE Outpatient Services Endorsement Add-On",
        file: "CO BHE Outpatient Endorsement Add-On.docx",
        pages: 14,
        slug: "co-bhe-outpatient-addon",
        agency: "Colorado BHA",
        citation: "2 CCR 502-1",
        policies: "Endorsement add-on — used alongside the BHE Base Manual",
        summary: "An add-on module for BHEs delivering outpatient behavioral health services. Use alongside the BHE Base Manual.",
        details: "This endorsement module layers the outpatient-specific policies onto your BHE Base Manual — outpatient service delivery, staffing, and documentation expectations under the Colorado BHA framework. It is not a standalone manual; pair it with the BHE Base Manual.",
        bullets: [
          "Outpatient behavioral health service delivery policies",
          "Outpatient staffing and supervision expectations",
          "Outpatient documentation and service planning",
          "Designed to attach to the BHE Base Manual",
          "Colorado BHA endorsement framework",
        ],
      },
      {
        id: "co-bhe-residential-addon",
        edition: "Residential & Withdrawal Endorsement",
        category: "Behavioral Health — Endorsement",
        title: "BHE Residential & Withdrawal Management Endorsement Add-On",
        file: "CO BHE Residential & Withdrawal Management Endorsement Add-On.docx",
        pages: 28,
        slug: "co-bhe-residential-addon",
        agency: "Colorado BHA",
        citation: "2 CCR 502-1",
        policies: "Endorsement add-on — used alongside the BHE Base Manual",
        summary: "An add-on module for BHEs delivering residential and withdrawal management services. Use alongside the BHE Base Manual.",
        details: "This endorsement module adds residential and withdrawal management policies to your BHE Base Manual — 24-hour residential service delivery, withdrawal management protocols, staffing, and safety under the Colorado BHA framework. Pair it with the BHE Base Manual.",
        bullets: [
          "Residential behavioral health service policies",
          "Withdrawal management protocols and monitoring",
          "24-hour staffing and coverage expectations",
          "Residential safety and environment standards",
          "Designed to attach to the BHE Base Manual",
        ],
      },
      {
        id: "co-bhe-crisis-addon",
        edition: "Emergency & Crisis Endorsement",
        category: "Behavioral Health — Endorsement",
        title: "BHE Emergency & Crisis Services Endorsement Add-On",
        file: "CO BHE Emergency & Crisis Services Endorsement Add-On.docx",
        pages: 24,
        slug: "co-bhe-crisis-addon",
        agency: "Colorado BHA",
        citation: "2 CCR 502-1",
        policies: "Endorsement add-on — used alongside the BHE Base Manual",
        summary: "An add-on module for BHEs delivering emergency and crisis services. Use alongside the BHE Base Manual.",
        details: "This endorsement module adds emergency and crisis service policies to your BHE Base Manual — crisis response, stabilization, and safety expectations under the Colorado BHA framework. Pair it with the BHE Base Manual.",
        bullets: [
          "Emergency and crisis service delivery policies",
          "Crisis response and stabilization protocols",
          "Safety and risk management in crisis settings",
          "Coordination and continuity of care",
          "Designed to attach to the BHE Base Manual",
        ],
      },
    ],
  },
  {
    id: "az",
    name: "Arizona",
    program: "Developmental Home Program",
    agency: "DES/DDD",
    citation: "A.A.C. R6-6-1101",
    manuals: [
      {
        id: "az-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Developmental Home Provider",
        file: "AZ_Individual_Provider_JC_FINAL.docx",
        pages: 71,
        slug: "az-individual",
        summary: "Built for individuals becoming an Arizona Developmental Home Provider under DES/DDD.",
        details: "Covers the Arizona DPS Fingerprint Clearance Card process, your Qualified Vendor relationship, ISP implementation, and the Life Safety Inspection required every two years. Every policy aligns with A.A.C. R6-6-1101 and OLCR oversight requirements.",
        bullets: [
          "Arizona DPS Fingerprint Clearance Card requirements",
          "Qualified Vendor relationship and ISP implementation",
          "Life Safety Inspection (every 2 years) and OLCR compliance",
          "DDD-approved medication administration training",
          "Article 9 behavioral support documentation",
        ],
      },
      {
        id: "az-agency",
        edition: "Qualified Vendor Agency",
        title: "Policy & Procedure Manual for Developmental Home Provider Agency",
        file: "AZ_Agency_QualifiedVendor_JC_FINAL.docx",
        pages: 69,
        slug: "az-agency",
        summary: "Built for Qualified Vendor agencies overseeing Arizona Developmental Homes.",
        details: "Covers Qualified Vendor certification and DDD oversight, developmental home provider contracting and Life Safety Inspection coordination, and the Arizona DPS clearance tracking required for every household member.",
        bullets: [
          "Qualified Vendor agency structure and DDD oversight",
          "Developmental home contracting and ongoing monitoring",
          "Arizona DPS background check and training requirements",
          "On-call coordinator and emergency coverage systems",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "az-bhrf",
        edition: "Residential (BHRF)",
        category: "Behavioral Health — Residential",
        title: "Behavioral Health Residential Facility (BHRF) Policy & Procedure Manual",
        file: "AZ Behavioral Health Residential Facility (BHRF) PP Manual.docx",
        pages: 123,
        slug: "az-bhrf",
        agency: "AZDHS",
        citation: "A.A.C. R9-10 Art. 7",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for an Arizona Behavioral Health Residential Facility licensed by AZDHS — covering 24-hour residential mental health and substance use treatment in one setting.",
        details: "Built to A.A.C. Title 9, Chapter 10, Article 7, this manual covers administration, personnel and fingerprint clearance, client rights, admission and assessment, treatment planning, medication, seclusion and restraint, environment and safety, and quality management for a BHRF providing residential behavioral health care.",
        bullets: [
          "AZDHS BHRF licensing framework (A.A.C. R9-10 Art. 7)",
          "24-hour residential mental health and substance use care",
          "Fingerprint Clearance Card and personnel requirements",
          "Admission, assessment, and treatment planning",
          "Client rights, seclusion/restraint, environment, and safety",
        ],
      },
      {
        id: "az-otc",
        edition: "Outpatient (OTC)",
        category: "Behavioral Health — Outpatient",
        title: "Outpatient Treatment Center (OTC) Policy & Procedure Manual",
        file: "AZ Outpatient Treatment Center (OTC) PP Manual.docx",
        pages: 86,
        slug: "az-otc",
        agency: "AZDHS",
        citation: "A.A.C. R9-10 Art. 19",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for an Arizona Outpatient Treatment Center licensed by AZDHS — outpatient behavioral health and substance use services.",
        details: "Built to A.A.C. Title 9, Chapter 10, Article 19, this manual covers administration, personnel, client rights, screening and assessment, outpatient treatment planning and service delivery, medication, records, and quality management for an outpatient treatment center.",
        bullets: [
          "AZDHS Outpatient Treatment Center framework (A.A.C. R9-10 Art. 19)",
          "Outpatient behavioral health and substance use services",
          "Fingerprint Clearance Card and personnel requirements",
          "Screening, assessment, and outpatient treatment planning",
          "Client rights, records, and quality management",
        ],
      },
    ],
  },
  {
    id: "fl",
    name: "Florida",
    program: "Foster Care Facility",
    agency: "APD",
    citation: "65G-2 F.A.C.",
    manuals: [
      {
        id: "fl-individual",
        edition: "Individual Operator",
        title: "Policy & Procedure Manual for Foster Care Facility Operator",
        file: "FL_Individual_Operator_JC_FINAL.docx",
        pages: 70,
        slug: "fl-individual",
        summary: "Built for individuals becoming a Florida Foster Care Facility Operator under APD.",
        details: "Covers the Level II background screening process through the AHCA Clearinghouse, your relationship with your MWSO, and the specific 65G-7 medication and 65G-8 behavioral support requirements that govern Florida's iBudget Waiver setting.",
        bullets: [
          "Level II background screening via AHCA Clearinghouse (§393.0655)",
          "APD, MWSO, and iBudget Waiver terminology throughout",
          "65G-7 medication management and 65G-8 reactive strategies",
          "APD monthly monitoring visit compliance",
          "Support Plan implementation and documentation standards",
        ],
      },
      {
        id: "fl-agency",
        edition: "Licensed Provider Agency",
        title: "Policy & Procedure Manual for Foster Care Facility Agency",
        file: "FL_Agency_LicensedProvider_JC_FINAL.docx",
        pages: 68,
        slug: "fl-agency",
        summary: "Built for APD-licensed agencies overseeing multiple Florida Foster Care Facilities.",
        details: "Covers agency-level AHCA Clearinghouse screening management, staff credentialing, APD licensing compliance, and the structure required to support multiple foster care facility operators under one organization.",
        bullets: [
          "APD licensed provider agency structure and oversight",
          "AHCA Clearinghouse process and staff credentialing",
          "APD monthly monitoring visit requirements",
          "Provider vetting, contracting, and ongoing supervision",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "fl-sud",
        edition: "Substance Abuse Services",
        category: "Behavioral Health — Substance Use",
        title: "Substance Abuse Services (DCF 65D-30) Policy & Procedure Manual",
        file: "FL Substance Abuse Services (DCF 65D-30) PP Manual.docx",
        pages: 82,
        slug: "fl-sud",
        agency: "Florida DCF",
        citation: "65D-30, F.A.C.",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Florida substance abuse services provider licensed by DCF under Chapter 65D-30.",
        details: "Built to Florida Administrative Code 65D-30, this manual covers licensure and administration, personnel and background screening, client rights and confidentiality (including 42 CFR Part 2), screening, assessment and placement, treatment planning and service delivery, medication, and quality improvement across the substance abuse service components.",
        bullets: [
          "Florida DCF 65D-30 licensing framework",
          "Substance abuse service components and levels of care",
          "Level II background screening via AHCA Clearinghouse",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Screening, assessment, placement, and treatment planning",
        ],
      },
      {
        id: "fl-mh",
        edition: "MH Residential Treatment",
        category: "Behavioral Health — Mental Health",
        title: "Mental Health Residential Treatment Facility (AHCA 65E-4.016) Policy & Procedure Manual",
        file: "FL Mental Health Residential Treatment Facility (AHCA 65E-4.016) PP Manual.docx",
        pages: 71,
        slug: "fl-mh",
        agency: "Florida AHCA / DCF",
        citation: "65E-4.016, F.A.C.",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Florida mental health residential treatment facility under Rule 65E-4.016.",
        details: "Built to Florida Administrative Code 65E-4.016, this manual covers administration, personnel, client rights, admission and assessment, residential treatment planning and service delivery, medication, seclusion and restraint, environment and safety, and quality improvement for a mental health residential treatment facility.",
        bullets: [
          "Florida 65E-4.016 mental health residential framework",
          "Residential mental health treatment planning and services",
          "Client rights, seclusion, and restraint",
          "Admission, assessment, and discharge planning",
          "Environment, safety, and quality improvement",
        ],
      },
    ],
  },
  {
    id: "tx",
    name: "Texas",
    program: "Host Home/Companion Care",
    agency: "HHSC",
    citation: "26 TAC Ch. 263",
    manuals: [
      {
        id: "tx-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Host Home/Companion Care Provider",
        file: "TX_Individual_HH_CC_Provider_JC_FINAL.docx",
        pages: 71,
        slug: "tx-individual",
        summary: "Built for individuals becoming a Texas HCS Host Home/Companion Care Provider under HHSC.",
        details: "Walks through Texas's three-part TULIP background clearance — DPS criminal history, the Employee Misconduct Registry, and the Nurse Aide Registry — plus your relationship with your Program Provider and LIDDA Service Coordinator, and the IPC/Implementation Plan structure unique to Texas.",
        bullets: [
          "TULIP three-part clearance: DPS criminal history, EMR, NAR",
          "Annual EMR and NAR re-verification requirements",
          "HHSC, LIDDA, Program Provider, IPC/IP terminology",
          "Substitute Caregiver background clearance and orientation",
          "26 TAC Ch. 263 and HCS Program Handbook compliance",
        ],
      },
      {
        id: "tx-agency",
        edition: "HCS Program Provider",
        title: "Policy & Procedure Manual for HCS Program Provider",
        file: "TX_Program_Provider_JC_FINAL.docx",
        pages: 68,
        slug: "tx-agency",
        summary: "Built for HHSC-contracted Program Providers overseeing multiple Texas HH/CC placements.",
        details: "Covers Program Provider contract obligations, TULIP background check oversight for every provider and household member, HH/CC provider vetting and home certification, and the site-specific Medicaid coordination required through HHSC.",
        bullets: [
          "HHSC Program Provider contract and TULIP oversight",
          "HH/CC provider vetting, contracting, and home certification",
          "IPC/Implementation Plan management procedures",
          "On-call coordinator and substitute caregiver coordination",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "tx-sud",
        edition: "Chemical Dependency",
        category: "Behavioral Health — Substance Use",
        title: "Chemical Dependency Treatment Facility (26 TAC 564) Policy & Procedure Manual",
        file: "TX Chemical Dependency Treatment Facility (26 TAC 564) PP Manual.docx",
        pages: 63,
        slug: "tx-sud",
        agency: "Texas HHSC",
        citation: "26 TAC Ch. 564",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Texas Chemical Dependency Treatment Facility licensed by HHSC under 26 TAC Chapter 564.",
        details: "Built to 26 Texas Administrative Code Chapter 564, this manual covers licensure and administration, personnel and background checks, client rights and confidentiality (including 42 CFR Part 2), screening and assessment, treatment planning and service delivery, medication, and quality management for a chemical dependency treatment facility.",
        bullets: [
          "Texas HHSC 26 TAC Ch. 564 licensing framework",
          "Chemical dependency treatment services and levels of care",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Screening, assessment, and treatment planning",
          "Personnel, background checks, and quality management",
        ],
      },
      {
        id: "tx-mh",
        edition: "Psychiatric Hospital & CSU",
        category: "Behavioral Health — Mental Health",
        title: "Private Psychiatric Hospital & Crisis Stabilization Unit (26 TAC 510) Policy & Procedure Manual",
        file: "TX Private Psychiatric Hospital & Crisis Stabilization Unit (26 TAC 510) PP Manual.docx",
        pages: 55,
        slug: "tx-mh",
        agency: "Texas HHSC",
        citation: "26 TAC Ch. 510",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Texas private psychiatric hospital or crisis stabilization unit licensed by HHSC under 26 TAC Chapter 510.",
        details: "Built to 26 Texas Administrative Code Chapter 510, this manual covers governance and administration, personnel, patient rights, admission and assessment, treatment planning, medication, seclusion and restraint, environment and life safety, and quality management for a private psychiatric hospital or crisis stabilization unit.",
        bullets: [
          "Texas HHSC 26 TAC Ch. 510 licensing framework",
          "Private psychiatric hospital and crisis stabilization unit",
          "Patient rights, seclusion, and restraint",
          "Admission, assessment, and treatment planning",
          "Environment, life safety, and quality management",
        ],
      },
    ],
  },
  {
    id: "nm",
    name: "New Mexico",
    program: "Family Living",
    agency: "DDSD / HCA",
    citation: "8.314.5 NMAC",
    manuals: [
      {
        id: "nm-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Family Living Provider",
        file: "NM_Individual_FamilyLiving_Provider_JC_FINAL.docx",
        pages: 73,
        slug: "nm-individual",
        summary: "Built for individuals becoming a New Mexico DDW Family Living Provider under DDSD.",
        details: "Walks through New Mexico's two-step background clearance — the COR/EAR check that must clear before care begins, and the CCHSP fingerprint check due within twenty calendar days — along with the two-person capacity limit, Therap documentation requirements, and the water temperature standard from DDW Numbered Memo 2025-03.",
        bullets: [
          "COR/EAR check before care begins, CCHSP within 20 days",
          "Two-person capacity limit under 8.314.5 NMAC",
          "Therap documentation requirements per DDSD",
          "Water temperature standard (DDW Numbered Memo 2025-03)",
          "PRN medication clarification per DDW Numbered Memo 2024-03",
        ],
      },
      {
        id: "nm-agency",
        edition: "DDW Provider Agency",
        title: "Policy & Procedure Manual for DDW Family Living Provider Agency",
        file: "NM_Provider_Agency_JC_FINAL.docx",
        pages: 70,
        slug: "nm-agency",
        summary: "Built for DDSD-contracted Provider Agencies overseeing multiple New Mexico Family Living homes.",
        details: "Covers agency-level COR/EAR and CCHSP clearance tracking, home study procedures, capacity limit compliance across all placements, Therap documentation oversight, and the DHI monitoring relationship required under DDW Service Standards.",
        bullets: [
          "DDSD Provider Agency contract and DHI oversight",
          "Family Living provider vetting and home study procedures",
          "Annual COR/EAR re-clearance tracking across all providers",
          "Therap documentation oversight and PRN medication compliance",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "nm-bha",
        edition: "Behavioral Health Agency",
        category: "Behavioral Health — Integrated",
        title: "Behavioral Health Agency (Substance Use & Mental Health) Policy & Procedure Manual",
        file: "NM Behavioral Health Agency (Substance Use & Mental Health) PP Manual.docx",
        pages: 66,
        slug: "nm-bha",
        agency: "New Mexico HCA / CYFD",
        citation: "8.321.2 NMAC",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a New Mexico behavioral health agency delivering both substance use and mental health services under 8.321.2 NMAC.",
        details: "Built to 8.321.2 NMAC, this integrated manual covers administration, personnel and background checks, client rights and confidentiality (including 42 CFR Part 2), screening and assessment, treatment planning and service delivery, medication, and quality management across both mental health and substance use services.",
        bullets: [
          "New Mexico 8.321.2 NMAC behavioral health agency framework",
          "Integrated substance use and mental health services",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Screening, assessment, and treatment planning",
          "Personnel, background checks, and quality management",
        ],
      },
    ],
  },
  {
    id: "ga",
    name: "Georgia",
    program: "Host Home / Life-Sharing",
    agency: "DBHDD",
    citation: "DBHDD Policy 02-704",
    manuals: [
      {
        id: "ga-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Host Home/Life-Sharing Provider",
        file: "GA_Individual_HostHome_Provider_JC_FINAL.docx",
        pages: 68,
        slug: "ga-individual",
        summary: "Built for individuals becoming a Georgia Host Home/Life-Sharing Provider under DBHDD.",
        details: "Covers the GCHEXS fingerprint background check process through IdentoGo, your relationship with your CRA Provider Agency and the Georgia Collaborative ASO, and the NOW/COMP Waiver terminology and capacity limits specific to Georgia's CRA services.",
        bullets: [
          "GCHEXS (IdentoGo) fingerprint background check process",
          "DBHDD, NOW/COMP Waiver, CRA, Georgia Collaborative ASO",
          "Two-person capacity limit per DBHDD Policy 02-704",
          "DDP role, Support Coordinator, and ISP enrollment procedures",
          "Relief caregiver background clearance and orientation",
        ],
      },
      {
        id: "ga-agency",
        edition: "CRA Provider Agency",
        title: "Policy & Procedure Manual for CRA Provider Agency",
        file: "GA_Agency_CRA_Provider_JC_FINAL.docx",
        pages: 67,
        slug: "ga-agency",
        summary: "Built for DBHDD-contracted CRA Provider Agencies overseeing multiple Georgia Host Homes.",
        details: "Covers DBHDD CRA agency certification, the Georgia Collaborative ASO enrollment process, the site-specific Medicaid provider number procedure required for every host home, and DDP attestation requirements under DBHDD oversight.",
        bullets: [
          "DBHDD CRA agency certification and ASO enrollment",
          "Site-specific Medicaid provider number process",
          "DDP attestation and GCHEXS oversight for all providers",
          "Host home vetting, contracting, and monitoring visits",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "ga-sud",
        edition: "Drug Abuse Treatment",
        category: "Behavioral Health — Substance Use",
        title: "Drug Abuse Treatment & Education Program (111-8-19) Policy & Procedure Manual",
        file: "GA Drug Abuse Treatment & Education Program (111-8-19) PP Manual.docx",
        pages: 55,
        slug: "ga-sud",
        agency: "Georgia DBHDD / DCH",
        citation: "Rule 111-8-19",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Georgia Drug Abuse Treatment & Education Program under Rule 111-8-19.",
        details: "Built to Georgia Rule 111-8-19, this manual covers licensure and administration, personnel and background checks, client rights and confidentiality (including 42 CFR Part 2), screening and assessment, treatment planning and service delivery, medication, and quality management for a drug abuse treatment and education program.",
        bullets: [
          "Georgia Rule 111-8-19 licensing framework",
          "Drug abuse treatment and education services",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Screening, assessment, and treatment planning",
          "Personnel, background checks, and quality management",
        ],
      },
      {
        id: "ga-mh",
        edition: "Adult Residential MH",
        category: "Behavioral Health — Mental Health",
        title: "Adult Residential Mental Health Program (111-8-2) Policy & Procedure Manual",
        file: "GA Adult Residential Mental Health Program (111-8-2) PP Manual.docx",
        pages: 51,
        slug: "ga-mh",
        agency: "Georgia DCH / HFRD",
        citation: "Rule 111-8-2",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Georgia Adult Residential Mental Health Program under Rule 111-8-2.",
        details: "Built to Georgia Rule 111-8-2, this manual covers licensure and administration, personnel and background checks, client rights and grievances, admission and assessment, residential treatment planning and service delivery, medication, safety, and quality management for an adult residential mental health program.",
        bullets: [
          "Georgia Rule 111-8-2 adult residential mental health framework",
          "Residential mental health treatment planning and services",
          "Client rights, grievances, and Disability Services Ombudsman",
          "Admission, assessment, and discharge planning",
          "Safety, environment, and quality management",
        ],
      },
    ],
  },
  {
    id: "ca",
    name: "California",
    program: "Family Home Agency (FHA)",
    agency: "DDS / Regional Center",
    citation: "Title 17 CCR §56075",
    manuals: [
      {
        id: "ca-individual",
        edition: "Individual Provider",
        title: "Policy & Procedure Manual for Family Home Provider (FHA)",
        file: "CA_Individual_FamilyHome_Provider_JC_FINAL.docx",
        pages: 70,
        slug: "ca-individual",
        summary: "Built for individuals becoming a California Family Home Provider under an FHA.",
        details: "Covers the DOJ LiveScan background check process through California's CBCB, the FHA and Regional Center relationship structure, and the IPP and consumer terminology used throughout California's DDS system — plus the additional privacy protections required under California's CMIA.",
        bullets: [
          "DOJ LiveScan background check (California CBCB)",
          "FHA, Regional Center, IPP, and consumer terminology",
          "HIPAA plus California CMIA privacy compliance",
          "FHA home study and ongoing monitoring requirements",
          "Relief caregiver background clearance and orientation",
        ],
      },
      {
        id: "ca-agency",
        edition: "Family Home Agency (FHA)",
        title: "Policy & Procedure Manual for Family Home Agency (FHA)",
        file: "CA_FamilyHomeAgency_JC_FINAL.docx",
        pages: 69,
        slug: "ca-agency",
        summary: "Built for Family Home Agencies vendored by a California Regional Center.",
        details: "Covers FHA vendorization through one of California's 21 Regional Centers, Title 17 CCR §56095 monitoring requirements, §56083 social service staff qualifications, and the DOJ LiveScan oversight required for every family home provider and household member.",
        bullets: [
          "FHA vendorization through a California Regional Center",
          "Title 17 CCR §56095 monitoring and §56083 staff qualifications",
          "FHA home study and DOJ LiveScan oversight",
          "Family home provider vetting and ongoing supervision",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "ca-sud",
        edition: "Residential AOD",
        category: "Behavioral Health — Substance Use",
        title: "Residential AOD Recovery or Treatment Facility (Title 9 Ch 5) Policy & Procedure Manual",
        file: "CA Residential AOD Recovery or Treatment Facility (Title 9 Ch5) PP Manual.docx",
        pages: 53,
        slug: "ca-sud",
        agency: "California DHCS",
        citation: "9 CCR, Ch. 5",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a California residential alcohol and other drug (AOD) recovery or treatment facility licensed by DHCS.",
        details: "Built to Title 9 of the California Code of Regulations, Chapter 5, this manual covers licensure and administration, personnel, client rights and confidentiality (including 42 CFR Part 2), admission and assessment, recovery and treatment planning and service delivery, incidental medical services, and quality management for a residential AOD facility.",
        bullets: [
          "California DHCS residential AOD licensing framework",
          "Residential recovery and treatment services",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Admission, assessment, and treatment planning",
          "Personnel, environment, and quality management",
        ],
      },
      {
        id: "ca-mh",
        edition: "MH Rehabilitation Center",
        category: "Behavioral Health — Mental Health",
        title: "Mental Health Rehabilitation Center (Title 9 Ch 3.5) Policy & Procedure Manual",
        file: "CA Mental Health Rehabilitation Center (Title 9 Ch 3.5) PP Manual.docx",
        pages: 52,
        slug: "ca-mh",
        agency: "California DHCS",
        citation: "9 CCR, Ch. 3.5",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a California Mental Health Rehabilitation Center (MHRC) licensed by DHCS under Title 9, Chapter 3.5.",
        details: "Built to Title 9 of the California Code of Regulations, Chapter 3.5, this manual covers licensure and the plan of operation, staffing, client rights and records, admission and the required assessments and mental health evaluation, the rehabilitation program, medication and basic services, seclusion and restraint, Brandon's Law family notification, and quality improvement for an MHRC.",
        bullets: [
          "California DHCS MHRC framework (9 CCR Ch. 3.5)",
          "Plan of operation and local behavioral health director role",
          "15-day assessment and 30-day mental health evaluation",
          "Seclusion/restraint (H&S Code Div. 1.5) and Brandon's Law",
          "Rehabilitation program, medication, and basic services",
        ],
      },
    ],
  },
  {
    id: "oh",
    name: "Ohio",
    program: "Ohio Shared Living",
    agency: "DODD",
    citation: "OAC 5123-9-33",
    manuals: [
      {
        id: "oh-individual",
        edition: "Independent Provider",
        title: "Policy & Procedure Manual for Shared Living Independent Provider",
        file: "OH_Individual_SharedLiving_Provider_JC_FINAL.docx",
        pages: 70,
        slug: "oh-individual",
        summary: "Built for individuals becoming an Ohio DODD Shared Living Independent Provider.",
        details: "Covers Ohio's BCI and FBI fingerprint clearance process, the DODD Abuse Registry check, your relationship with your County Board SSA, and the Medication Administration Certification and nurse delegation requirements specific to non-related caregivers under OAC 5123-9-33.",
        bullets: [
          "BCI + FBI fingerprint clearance and DODD Abuse Registry check",
          "DODD, SSA, County Board of DD, ISP terminology",
          "MUI/UI incident reporting (Ohio-specific terms)",
          "Medication Administration Certification and nurse delegation",
          "Four-person capacity limit and primary residence requirement",
        ],
      },
      {
        id: "oh-agency",
        edition: "Agency Provider",
        title: "Policy & Procedure Manual for Shared Living Agency Provider",
        file: "OH_Agency_SharedLiving_Provider_JC_FINAL.docx",
        pages: 69,
        slug: "oh-agency",
        summary: "Built for DODD-certified Agency Providers overseeing multiple Ohio Shared Living caregivers.",
        details: "Covers DODD Agency Provider certification through the PSM system, Director of Operations and QIDP qualifications, shared living caregiver contracting and primary residence verification, and the monthly UI Log review process required under DODD policy.",
        bullets: [
          "DODD Agency Provider certification (OAC 5123-2-08) via PSM",
          "Director of Operations and QIDP qualifications",
          "Shared living caregiver contracting and monitoring",
          "Monthly UI Log review and MUI reporting requirements",
          "Quality management and corrective action procedures",
        ],
      },
      {
        id: "oh-bh",
        edition: "Behavioral Health Provider",
        category: "Behavioral Health — Integrated",
        title: "Behavioral Health Provider (OhioMHAS) Policy & Procedure Manual",
        file: "OH Behavioral Health Provider (OhioMHAS) PP Manual.docx",
        pages: 56,
        slug: "oh-bh",
        agency: "OhioMHAS",
        citation: "OAC 5122",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for an Ohio behavioral health provider certified by OhioMHAS — covering both mental health and substance use disorder services.",
        details: "Built to Ohio Administrative Code Chapter 5122, this integrated manual covers certification and administration, personnel and background checks, client rights and grievances, confidentiality (including 42 CFR Part 2), screening and assessment, treatment planning and service delivery, medication, and quality management across mental health and substance use disorder services.",
        bullets: [
          "OhioMHAS certification framework (OAC 5122)",
          "Integrated mental health and substance use disorder services",
          "Client rights, grievances, and confidentiality (42 CFR Part 2)",
          "Screening, assessment, and treatment planning",
          "Personnel, background checks, and quality management",
        ],
      },
    ],
  },
  {
    id: "wi",
    name: "Wisconsin",
    program: "Behavioral Health",
    agency: "WI DHS (DQA)",
    citation: "DHS 75 / DHS 35",
    manuals: [
      {
        id: "wi-sud",
        edition: "Substance Use Service",
        category: "Behavioral Health — Substance Use",
        title: "Community Substance Use Service (DHS 75) Policy & Procedure Manual",
        file: "WI Community Substance Use Service (DHS 75) PP Manual.docx",
        pages: 64,
        slug: "wi-sud",
        agency: "WI DHS (DQA)",
        citation: "DHS 75",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Wisconsin community substance use service certified under DHS 75.",
        details: "Built to Wisconsin Administrative Code DHS 75, this manual covers certification and administration, personnel, client rights and confidentiality (including 42 CFR Part 2), screening, assessment and placement, treatment planning and service delivery, medication, and quality management across the DHS 75 substance use service levels.",
        bullets: [
          "Wisconsin DHS 75 certification framework",
          "Community substance use service levels of care",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Screening, assessment, placement, and treatment planning",
          "Personnel, medication, and quality management",
        ],
      },
      {
        id: "wi-mh",
        edition: "Outpatient MH Clinic",
        category: "Behavioral Health — Mental Health",
        title: "Outpatient Mental Health Clinic (DHS 35) Policy & Procedure Manual",
        file: "WI Outpatient Mental Health Clinic (DHS 35) PP Manual.docx",
        pages: 52,
        slug: "wi-mh",
        agency: "WI DHS (DQA)",
        citation: "DHS 35",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Wisconsin outpatient mental health clinic certified under DHS 35.",
        details: "Built to Wisconsin Administrative Code DHS 35, this manual covers certification and administration, clinic staffing and clinical supervision, consumer rights and confidentiality, intake and assessment, treatment planning and service delivery, medication, and quality management for an outpatient mental health clinic.",
        bullets: [
          "Wisconsin DHS 35 outpatient mental health clinic framework",
          "Clinic staffing and clinical supervision requirements",
          "Consumer rights and confidentiality",
          "Intake, assessment, and treatment planning",
          "Medication and quality management",
        ],
      },
    ],
  },
  {
    id: "ar",
    name: "Arkansas",
    program: "Behavioral Health",
    agency: "AR DHS (DAABHS / DPSQA)",
    citation: "OADAP Part 433 / OBHS",
    manuals: [
      {
        id: "ar-sud",
        edition: "Alcohol & Drug (OADAP)",
        category: "Behavioral Health — Substance Use",
        title: "Alcohol & Other Drug Abuse Treatment Program (OADAP Part 433) Policy & Procedure Manual",
        file: "AR Alcohol & Other Drug Abuse Treatment Program (OADAP Part 433) PP Manual.docx",
        pages: 54,
        slug: "ar-sud",
        agency: "Arkansas DHS (DAABHS)",
        citation: "OADAP Part 433",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for an Arkansas alcohol and other drug abuse treatment program under the OADAP Part 433 licensure standards.",
        details: "Built to the Arkansas OADAP Part 433 standards, this manual covers licensure and administration, personnel and background checks, client rights and confidentiality (including 42 CFR Part 2), screening and assessment, treatment planning and service delivery, medication, and quality management for an alcohol and other drug abuse treatment program.",
        bullets: [
          "Arkansas OADAP Part 433 licensing framework",
          "Alcohol and other drug abuse treatment services",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Screening, assessment, and treatment planning",
          "Personnel, background checks, and quality management",
        ],
      },
      {
        id: "ar-mh",
        edition: "Behavioral Health Agency (Outpatient)",
        category: "Behavioral Health — Mental Health",
        title: "Behavioral Health Agency (Outpatient Behavioral Health Services) Policy & Procedure Manual",
        file: "AR Behavioral Health Agency (Outpatient Behavioral Health Services) PP Manual.docx",
        pages: 53,
        slug: "ar-mh",
        agency: "Arkansas DHS (DPSQA / DAABHS)",
        citation: "Ark. Admin. Code (OBHS)",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for an Arkansas Behavioral Health Agency delivering Outpatient Behavioral Health Services (OBHS).",
        details: "Built to the Arkansas Outpatient Behavioral Health Services (OBHS) standards, this manual covers certification and administration, personnel and background checks, client rights and confidentiality, independent assessment and levels of service (counseling, rehabilitative, intensive), treatment planning and service delivery, medication, and quality management for a behavioral health agency.",
        bullets: [
          "Arkansas OBHS behavioral health agency framework",
          "Independent assessment and counseling/rehabilitative/intensive levels",
          "Client rights and confidentiality",
          "QBHP-under-MHP staffing and Medical Director requirements",
          "Treatment planning, medication, and quality management",
        ],
      },
    ],
  },
  {
    id: "tn",
    name: "Tennessee",
    program: "Behavioral Health",
    agency: "TDMHSAS",
    citation: "0940-05",
    manuals: [
      {
        id: "tn-sud",
        edition: "Alcohol & Drug Facility",
        category: "Behavioral Health — Substance Use",
        title: "Alcohol & Drug Treatment Facility (TDMHSAS 0940-05) Policy & Procedure Manual",
        file: "TN Alcohol & Drug Treatment Facility (TDMHSAS 0940-05) PP Manual.docx",
        pages: 56,
        slug: "tn-sud",
        agency: "Tennessee TDMHSAS",
        citation: "Rules 0940-05",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Tennessee alcohol and drug treatment facility licensed by TDMHSAS under Chapter 0940-05.",
        details: "Built to the TDMHSAS rules in Chapter 0940-05, this manual covers licensure and administration, personnel and background checks, service recipient rights and confidentiality (including 42 CFR Part 2), screening and assessment, treatment planning and service delivery, medication, and quality management for an alcohol and drug treatment facility.",
        bullets: [
          "Tennessee TDMHSAS 0940-05 licensing framework",
          "Alcohol and drug treatment services",
          "Service recipient rights and confidentiality (42 CFR Part 2)",
          "Screening, assessment, and treatment planning",
          "Personnel, background checks, and quality management",
        ],
      },
      {
        id: "tn-mh",
        edition: "Adult Residential MH",
        category: "Behavioral Health — Mental Health",
        title: "Mental Health Adult Residential Treatment Program (0940-05-17) Policy & Procedure Manual",
        file: "TN Mental Health Adult Residential Treatment Program (0940-05-17) PP Manual.docx",
        pages: 53,
        slug: "tn-mh",
        agency: "Tennessee TDMHSAS",
        citation: "0940-05-17",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Tennessee mental health adult residential treatment program licensed by TDMHSAS under Chapter 0940-05-17.",
        details: "Built to TDMHSAS Chapter 0940-05-17, this manual covers licensure and administration, personnel and the required staffing ratios, service recipient rights and records, admission and assessment, the 72-hour and 30-day plan-of-care requirements, medication, disruptive-behavior and restraint requirements, emergency services, and quality management.",
        bullets: [
          "Tennessee TDMHSAS 0940-05-17 residential framework",
          "24-hour intensive residential mental health treatment",
          "Required direct-care staffing ratios and coverage",
          "72-hour and 30-day plan-of-care requirements",
          "Rights, restraint (0940-03-09), and emergency services",
        ],
      },
    ],
  },
  {
    id: "sc",
    name: "South Carolina",
    program: "Behavioral Health",
    agency: "SC DPH",
    citation: "R.60-103 / R.61-93",
    manuals: [
      {
        id: "sc-sud",
        edition: "Substance Abuse/Dependence",
        category: "Behavioral Health — Substance Use",
        title: "Facility Treating Psychoactive Substance Abuse or Dependence (R.61-93) Policy & Procedure Manual",
        file: "SC Facility Treating Psychoactive Substance Abuse or Dependence (R.61-93) PP Manual.docx",
        pages: 52,
        slug: "sc-sud",
        agency: "SC DPH",
        citation: "R.61-93",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a South Carolina facility treating psychoactive substance abuse or dependence, licensed by DPH under Regulation 61-93.",
        details: "Built to South Carolina Regulation 61-93, this manual covers licensure and administration, personnel and background checks, client rights and confidentiality (including 42 CFR Part 2), admission and assessment, treatment planning and service delivery, medication, environment and safety, and quality improvement for a substance abuse/dependence treatment facility.",
        bullets: [
          "South Carolina R.61-93 licensing framework (DPH)",
          "Psychoactive substance abuse/dependence treatment services",
          "Client rights and confidentiality (42 CFR Part 2)",
          "Admission, assessment, and treatment planning",
          "Environment, safety, and quality improvement",
        ],
      },
      {
        id: "sc-mh",
        edition: "RTF — Children & Adolescents",
        category: "Behavioral Health — Mental Health",
        title: "Residential Treatment Facility for Children & Adolescents (R.60-103) Policy & Procedure Manual",
        file: "SC Residential Treatment Facility for Children & Adolescents (R.60-103) PP Manual.docx",
        pages: 62,
        slug: "sc-mh",
        agency: "SC DPH",
        citation: "R.60-103",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a South Carolina Residential Treatment Facility for Children and Adolescents, licensed by the Department of Public Health under Regulation 60-103.",
        details: "Built to South Carolina Regulation 60-103 (most recently amended in 2026), this manual covers licensure and enforcement, staff and training with the required direct-care ratios, resident rights and records, admission, assessment and treatment planning, resident care, health and medication, and environment, safety, and emergency requirements for a youth residential mental health treatment facility.",
        bullets: [
          "South Carolina R.60-103 framework (DPH; amended 2026)",
          "Residential mental health treatment for children and adolescents",
          "Direct-care staffing ratios and suicide-watch monitoring",
          "Admission determination, assessment, and treatment planning",
          "Resident rights, restraint/seclusion, medication, and safety",
        ],
      },
    ],
  },
  {
    id: "va",
    name: "Virginia",
    program: "Behavioral Health",
    agency: "VA DBHDS",
    citation: "12VAC35-105",
    manuals: [
      {
        id: "va-sud",
        edition: "Substance Use Provider",
        category: "Behavioral Health — Substance Use",
        title: "Substance Use Disorder Provider (DBHDS 12VAC35-105) Policy & Procedure Manual",
        file: "VA Substance Use Disorder Provider (DBHDS 12VAC35-105) PP Manual.docx",
        pages: 58,
        slug: "va-sud",
        agency: "Virginia DBHDS",
        citation: "12VAC35-105",
        policies: "Structured in six sections (A–F), plus appendices",
        summary: "A comprehensive manual for a Virginia substance use disorder provider licensed by DBHDS under 12VAC35-105.",
        details: "Built to Virginia 12VAC35-105 (the DBHDS Rules and Regulations for Licensing Providers), this manual covers licensure and administration, personnel and background checks, individual rights and confidentiality (including 42 CFR Part 2), screening and assessment, the individualized services plan and service delivery, medication, risk management, and quality improvement for a substance use disorder provider.",
        bullets: [
          "Virginia DBHDS 12VAC35-105 licensing framework",
          "Substance use disorder services and levels of care",
          "Individual rights and confidentiality (42 CFR Part 2)",
          "Assessment and the individualized services plan (ISP)",
          "Risk management and quality improvement",
        ],
      },
    ],
  },
];

// Flat lookup for manual.html
function findManual(slug) {
  for (const state of STATES) {
    const m = state.manuals.find((m) => m.slug === slug);
    if (m) return { ...m, state };
  }
  return null;
}

// Flat lookup for state.html
function findState(id) {
  return STATES.find((s) => s.id === id) || null;
}
