// catalog.js \u2014 single source of truth for what can be purchased and delivered.
//
// Every manual is a flat $200. Stripe does NOT need a product/price created for
// each one: the checkout function builds a $200 line item on the fly and stores
// the manual's `slug` in the session metadata. This file maps that slug to the
// display title (shown on the Stripe checkout page) and the file to deliver
// (the .docx must sit in api/_files/ with the exact name below).
//
// >>> THE ONE INTEGRATION SEAM <<<
// The `slug` values below MUST match the slugs your site already uses in data.js
// and in your product/state detail URLs. Keep this file as the source of truth
// and make data.js use the same slugs, OR replace PRODUCTS by importing data.js.
// Everything else in this integration reads through getProduct().

const PRICE_CENTS = 20000;        // $200.00 \u2014 companion products: how-to guides, forms packets, employee handbooks
const MANUAL_PRICE_CENTS = 50000; // $500.00 \u2014 policy & procedure manuals and manual add-ons
const CURRENCY = "usd";

// Price rule (keep in sync with manual.html):
// A product is a $200 companion ONLY if it is a how-to guide (slug contains
// "-open-"), a forms packet (slug ends "-forms"), or an employee handbook
// (slug ends "-handbook"). Everything else \u2014 manuals and add-ons \u2014 is $500.
function priceForSlug(slug) {
  const s = String(slug || "");
  const isCompanion = s.includes("-open-") || s.endsWith("-forms") || s.endsWith("-handbook") || s.includes("referral");
  return isCompanion ? PRICE_CENTS : MANUAL_PRICE_CENTS;
}

// slug: { title (shown at checkout), file (delivered .docx in api/_files/) }
const PRODUCTS = {
  // ===== Host Home / IDD Residential line (original) =====
  'co-individual': { title: 'Policy & Procedure Manual for Host Home Provider (Colorado)', file: 'CO_Individual_Provider_JC_FINAL.docx' },
  'co-agency': { title: 'Policy & Procedure Manual for Host Home Provider Agency (Colorado)', file: 'CO_Agency_PASA_JC_FINAL.docx' },
  'az-individual': { title: 'Policy & Procedure Manual for Developmental Home Provider (Arizona)', file: 'AZ_Individual_Provider_JC_FINAL.docx' },
  'az-agency': { title: 'Policy & Procedure Manual for Developmental Home Provider Agency (Arizona)', file: 'AZ_Agency_QualifiedVendor_JC_FINAL.docx' },
  'fl-individual': { title: 'Policy & Procedure Manual for Foster Care Facility Operator (Florida)', file: 'FL_Individual_Operator_JC_FINAL.docx' },
  'fl-agency': { title: 'Policy & Procedure Manual for Foster Care Facility Agency (Florida)', file: 'FL_Agency_LicensedProvider_JC_FINAL.docx' },
  'tx-individual': { title: 'Policy & Procedure Manual for Host Home/Companion Care Provider (Texas)', file: 'TX_Individual_HH_CC_Provider_JC_FINAL.docx' },
  'tx-agency': { title: 'Policy & Procedure Manual for HCS Program Provider (Texas)', file: 'TX_Program_Provider_JC_FINAL.docx' },
  'nm-individual': { title: 'Policy & Procedure Manual for Family Living Provider (New Mexico)', file: 'NM_Individual_FamilyLiving_Provider_JC_FINAL.docx' },
  'nm-agency': { title: 'Policy & Procedure Manual for DDW Family Living Provider Agency (New Mexico)', file: 'NM_Provider_Agency_JC_FINAL.docx' },
  'ga-individual': { title: 'Policy & Procedure Manual for Host Home/Life-Sharing Provider (Georgia)', file: 'GA_Individual_HostHome_Provider_JC_FINAL.docx' },
  'ga-agency': { title: 'Policy & Procedure Manual for CRA Provider Agency (Georgia)', file: 'GA_Agency_CRA_Provider_JC_FINAL.docx' },
  'ca-individual': { title: 'Policy & Procedure Manual for Family Home Provider - FHA (California)', file: 'CA_Individual_FamilyHome_Provider_JC_FINAL.docx' },
  'ca-agency': { title: 'Policy & Procedure Manual for Family Home Agency - FHA (California)', file: 'CA_FamilyHomeAgency_JC_FINAL.docx' },
  'oh-individual': { title: 'Policy & Procedure Manual for Shared Living Independent Provider (Ohio)', file: 'OH_Individual_SharedLiving_Provider_JC_FINAL.docx' },
  'oh-agency': { title: 'Policy & Procedure Manual for Shared Living Agency Provider (Ohio)', file: 'OH_Agency_SharedLiving_Provider_JC_FINAL.docx' },
  'tn-individual': { title: 'Policy & Procedure Manual for Family Model Residential (Host Home) Provider (Tennessee)', file: 'TN_Individual_HostHome_PP_Manual.docx' },
  'tn-agency': { title: 'Policy & Procedure Manual for Family Model Residential (Host Home) Provider Agency (Tennessee)', file: 'TN_Agency_HostHome_PP_Manual.docx' },
  'va-individual': { title: 'Policy & Procedure Manual for Sponsored Residential Provider (Virginia)', file: 'VA_Individual_HostHome_PP_Manual.docx' },
  'va-agency': { title: 'Policy & Procedure Manual for Sponsored Residential Provider Agency (Virginia)', file: 'VA_Agency_HostHome_PP_Manual.docx' },
  'sc-individual': { title: 'Policy & Procedure Manual for Community Training Home (CTH-I) Host-Family Provider (South Carolina)', file: 'SC_Individual_HostHome_PP_Manual.docx' },
  'sc-agency': { title: 'Policy & Procedure Manual for Community Training Home / Residential Habilitation Provider Agency (South Carolina)', file: 'SC_Agency_HostHome_PP_Manual.docx' },
  'wi-individual': { title: 'Policy & Procedure Manual for Certified 1-2 Bed Adult Family Home Operator (Wisconsin)', file: 'WI_Individual_HostHome_PP_Manual.docx' },
  'wi-agency': { title: 'Policy & Procedure Manual for 1-2 Bed Adult Family Home Provider Agency (Wisconsin)', file: 'WI_Agency_HostHome_PP_Manual.docx' },

  // ===== Behavioral Health \u2014 Substance Use (SUD) line =====
  "co-bhe": { title: "Colorado Behavioral Health Entity (BHE) Base Policy & Procedure Manual", file: "CO Behavioral Health Entity (BHE) Base PP Manual.docx" },
  "co-bhe-referral": { title: "The Behavioral Health Referral System (Colorado Edition)", file: "The_Behavioral_Health_Referral_System_Colorado_Edition.docx" },
  "co-bhe-outpatient-addon": { title: "Colorado BHE Outpatient Endorsement Add-On", file: "CO BHE Outpatient Endorsement Add-On.docx" },
  "co-bhe-residential-addon": { title: "Colorado BHE Residential & Withdrawal Management Endorsement Add-On", file: "CO BHE Residential & Withdrawal Management Endorsement Add-On.docx" },
  "co-bhe-crisis-addon": { title: "Colorado BHE Emergency & Crisis Services Endorsement Add-On", file: "CO BHE Emergency & Crisis Services Endorsement Add-On.docx" },
  "az-bhrf": { title: "Arizona Behavioral Health Residential Facility (BHRF) Policy & Procedure Manual", file: "AZ Behavioral Health Residential Facility (BHRF) PP Manual.docx" },
  "az-otc": { title: "Arizona Outpatient Treatment Center (OTC) Policy & Procedure Manual", file: "AZ Outpatient Treatment Center (OTC) PP Manual.docx" },
  "az-bh-referral": { title: "The Behavioral Health Referral System (Arizona Edition)", file: "The_Behavioral_Health_Referral_System_Arizona_Edition.docx" },
  "fl-sud": { title: "Florida Substance Abuse Services (DCF 65D-30) Policy & Procedure Manual", file: "FL Substance Abuse Services (DCF 65D-30) PP Manual.docx" },
  "tx-sud": { title: "Texas Chemical Dependency Treatment Facility (26 TAC 564) Policy & Procedure Manual", file: "TX Chemical Dependency Treatment Facility (26 TAC 564) PP Manual.docx" },
  "nm-bha": { title: "New Mexico Behavioral Health Agency (Substance Use & Mental Health) Policy & Procedure Manual", file: "NM Behavioral Health Agency (Substance Use & Mental Health) PP Manual.docx" },
  "nm-bha-referral": { title: "The Behavioral Health Referral System (New Mexico Edition)", file: "The_Behavioral_Health_Referral_System_New_Mexico_Edition.docx" },
  "ga-sud": { title: "Georgia Drug Abuse Treatment & Education Program (111-8-19) Policy & Procedure Manual", file: "GA Drug Abuse Treatment & Education Program (111-8-19) PP Manual.docx" },
  "ca-sud": { title: "California Residential AOD Recovery or Treatment Facility (Title 9 Ch5) Policy & Procedure Manual", file: "CA Residential AOD Recovery or Treatment Facility (Title 9 Ch5) PP Manual.docx" },
  "oh-bh": { title: "Ohio Behavioral Health Provider (OhioMHAS) Policy & Procedure Manual", file: "OH Behavioral Health Provider (OhioMHAS) PP Manual.docx" },
  "wi-sud": { title: "Wisconsin Community Substance Use Service (DHS 75) Policy & Procedure Manual", file: "WI Community Substance Use Service (DHS 75) PP Manual.docx" },
  "ar-sud": { title: "Arkansas Alcohol & Other Drug Abuse Treatment Program (OADAP Part 433) Policy & Procedure Manual", file: "AR Alcohol & Other Drug Abuse Treatment Program (OADAP Part 433) PP Manual.docx" },
  "ar-home-care": { title: "Arkansas Private Care Agency Policy & Procedure Manual", file: "AR_Home_Care_PP_Manual.docx" },
  "ar-open-home-care": { title: "How to Open an In-Home Care Agency in Arkansas", file: "How_to_Open_an_In_Home_Care_Agency_in_Arkansas.pdf" },
  "ar-home-care-handbook": { title: "Arkansas In-Home Care Caregiver Handbook", file: "AR_Home_Care_Caregiver_Handbook.docx" },
  "ar-home-care-forms": { title: "Arkansas Private Care Agency Forms Packet", file: "AR_Home_Care_Forms_Packet.docx" },
  "ar-referral-system": { title: "The Referral System \u2014 Arkansas Edition", file: "The_Referral_System_Arkansas_Edition.docx" },
  "tn-sud": { title: "Tennessee Alcohol & Drug Treatment Facility (TDMHSAS 0940-05) Policy & Procedure Manual", file: "TN Alcohol & Drug Treatment Facility (TDMHSAS 0940-05) PP Manual.docx" },
  "sc-sud": { title: "South Carolina Facility Treating Psychoactive Substance Abuse or Dependence (R.61-93) Policy & Procedure Manual", file: "SC Facility Treating Psychoactive Substance Abuse or Dependence (R.61-93) PP Manual.docx" },
  "va-sud": { title: "Virginia Substance Use Disorder Provider (DBHDS 12VAC35-105) Policy & Procedure Manual", file: "VA Substance Use Disorder Provider (DBHDS 12VAC35-105) PP Manual.docx" },
  "va-mh": { title: "Mental Health Services (DBHDS 12VAC35-105) Policy & Procedure Manual", file: "VA Mental Health Services (DBHDS 12VAC35-105) PP Manual.docx" },

  // ===== Mental Health (MH) line =====
  "fl-mh": { title: "Florida Mental Health Residential Treatment Facility (AHCA 65E-4.016) Policy & Procedure Manual", file: "FL Mental Health Residential Treatment Facility (AHCA 65E-4.016) PP Manual.docx" },
  "fl-sud-referral": { title: "The Substance Use Referral System (Florida Edition)", file: "The_Substance_Use_Referral_System_Florida_Edition.docx" },
  "fl-mh-referral": { title: "The Mental Health Referral System (Florida Edition)", file: "The_Mental_Health_Referral_System_Florida_Edition.docx" },
  "tx-mh": { title: "Texas Private Psychiatric Hospital & Crisis Stabilization Unit (26 TAC 510) Policy & Procedure Manual", file: "TX Private Psychiatric Hospital & Crisis Stabilization Unit (26 TAC 510) PP Manual.docx" },
  "tx-sud-referral": { title: "The Substance Use Referral System (Texas Edition)", file: "The_Substance_Use_Referral_System_Texas_Edition.docx" },
  "tx-mh-referral": { title: "The Mental Health Referral System (Texas Edition)", file: "The_Mental_Health_Referral_System_Texas_Edition.docx" },
  "tx-mh-lmha": { title: "Community Mental Health Services (LMHA \u2014 26 TAC 301 & 306) Policy & Procedure Manual", file: "TX Community Mental Health (LMHA - 26 TAC 301 & 306) PP Manual.docx" },
  "ga-mh": { title: "Georgia Adult Residential Mental Health Program (111-8-2) Policy & Procedure Manual", file: "GA Adult Residential Mental Health Program (111-8-2) PP Manual.docx" },
  "ga-sud-referral": { title: "The Substance Use Referral System (Georgia Edition)", file: "The_Substance_Use_Referral_System_Georgia_Edition.docx" },
  "ga-mh-referral": { title: "The Mental Health Referral System (Georgia Edition)", file: "The_Mental_Health_Referral_System_Georgia_Edition.docx" },
  "wi-mh": { title: "Wisconsin Outpatient Mental Health Clinic (DHS 35) Policy & Procedure Manual", file: "WI Outpatient Mental Health Clinic (DHS 35) PP Manual.docx" },
  "ar-mh": { title: "Arkansas Behavioral Health Agency (Outpatient Behavioral Health Services) Policy & Procedure Manual", file: "AR Behavioral Health Agency (Outpatient Behavioral Health Services) PP Manual.docx" },
  "tn-mh": { title: "Tennessee Mental Health Adult Residential Treatment Program (0940-05-17) Policy & Procedure Manual", file: "TN Mental Health Adult Residential Treatment Program (0940-05-17) PP Manual.docx" },
  "ca-mh": { title: "California Mental Health Rehabilitation Center (Title 9 Ch 3.5) Policy & Procedure Manual", file: "CA Mental Health Rehabilitation Center (Title 9 Ch 3.5) PP Manual.docx" },
  "ca-sud-referral": { title: "The Substance Use Referral System (California Edition)", file: "The_Substance_Use_Referral_System_California_Edition.docx" },
  "ca-mh-referral": { title: "The Mental Health Referral System (California Edition)", file: "The_Mental_Health_Referral_System_California_Edition.docx" },
  "sc-mh": { title: "South Carolina Residential Treatment Facility for Children & Adolescents (R.60-103) Policy & Procedure Manual", file: "SC Residential Treatment Facility for Children & Adolescents (R.60-103) PP Manual.docx" },

  // ===== Assisted Living / Residential Care line =====
  "az-al-personal-care": { title: "Arizona Assisted Living Personal Care Policy & Procedure Manual", file: "AZ Assisted Living Personal Care PP Manual.docx" },
  "az-al-directed-care": { title: "Arizona Assisted Living Directed Care Policy & Procedure Manual", file: "AZ Assisted Living Directed Care PP Manual.docx" },
  "az-al-supervisory-care": { title: "Arizona Assisted Living Supervisory Care Policy & Procedure Manual", file: "AZ Assisted Living Supervisory Care PP Manual.docx" },
  "ar-alf-level-1": { title: "Arkansas Assisted Living Facility Level I Policy & Procedure Manual", file: "AR Assisted Living Facility Level I PP Manual.docx" },
  "ar-alf-level-2": { title: "Arkansas Assisted Living Facility Level II Policy & Procedure Manual", file: "AR Assisted Living Facility Level II PP Manual.docx" },
  "ca-rcfe": { title: "California Residential Care Facility for the Elderly (RCFE) Policy & Procedure Manual", file: "CA Residential Care Facility for the Elderly (RCFE) PP Manual.docx" },
  "co-alr": { title: "Colorado Assisted Living Residence Policy & Procedure Manual", file: "CO Assisted Living Residence PP Manual.docx" },
  "fl-al-standard": { title: "Florida Assisted Living Standard License Policy & Procedure Manual", file: "FL Assisted Living Standard License PP Manual.docx" },
  "fl-al-ecc-addon": { title: "Florida Assisted Living ECC Add-On", file: "FL Assisted Living ECC Add-On.docx" },
  "fl-al-lmh-addon": { title: "Florida Assisted Living LMH Add-On", file: "FL Assisted Living LMH Add-On.docx" },
  "fl-al-lns-addon": { title: "Florida Assisted Living LNS Add-On", file: "FL Assisted Living LNS Add-On.docx" },
  "ga-alc": { title: "Georgia Assisted Living Community (ALC) Policy & Procedure Manual", file: "GA Assisted Living Community (ALC) PP Manual.docx" },
  "ga-pch": { title: "Georgia Personal Care Home (PCH) Policy & Procedure Manual", file: "GA Personal Care Home (PCH) PP Manual.docx" },
  "nm-al": { title: "New Mexico Assisted Living Policy & Procedure Manual", file: "NM Assisted Living PP Manual.docx" },
  "oh-rcf": { title: "Ohio Residential Care Facility (RCF) Policy & Procedure Manual", file: "OH Residential Care Facility (RCF) PP Manual.docx" },
  "sc-crcf": { title: "South Carolina Community Residential Care Facility (CRCF) Policy & Procedure Manual", file: "SC Community Residential Care Facility (CRCF) PP Manual.docx" },
  "tn-aclf": { title: "Tennessee Assisted-Care Living Facility (ACLF) Policy & Procedure Manual", file: "TN Assisted-Care Living Facility (ACLF) PP Manual.docx" },
  "tn-rha": { title: "Tennessee Residential Home for the Aged (RHA) Policy & Procedure Manual", file: "TN Residential Home for the Aged (RHA) PP Manual.docx" },
  "tn-home-care": { title: "Tennessee Personal Support Services Agency (PSSA) Policy & Procedure Manual", file: "TN_Home_Care_PP_Manual.docx" },
  "tn-open-home-care": { title: "How to Open a Home Care Agency in Tennessee", file: "How_to_Open_a_Home_Care_Agency_in_Tennessee.pdf" },
  "tn-home-care-handbook": { title: "Tennessee Personal Support Services Agency (PSSA) Caregiver Handbook", file: "TN_Home_Care_Caregiver_Handbook.docx" },
  "tn-home-care-forms": { title: "Tennessee Personal Support Services Agency (PSSA) Forms Packet", file: "TN_Home_Care_Forms_Packet.docx" },
  "tn-referral-system": { title: "The Referral System \u2014 Tennessee Edition", file: "The_Referral_System_Tennessee_Edition.docx" },
  "va-home-care": { title: "Home Care Organization Policy & Procedure Manual", file: "VA_Home_Care_PP_Manual.docx" },
  "va-open-home-care": { title: "How to Open a Home Care Agency in Virginia", file: "How_to_Open_a_Home_Care_Agency_in_Virginia.pdf" },
  "va-home-care-handbook": { title: "Home Care Caregiver Handbook (Virginia)", file: "VA_Home_Care_Caregiver_Handbook.docx" },
  "va-home-care-forms": { title: "Home Care Organization Forms Packet (Virginia)", file: "VA_Home_Care_Forms_Packet.docx" },
  "va-referral-system": { title: "The Referral System \u2014 Virginia Edition", file: "The_Referral_System_Virginia_Edition.docx" },
  "tx-al-type-ab": { title: "Texas Assisted Living Type A and B Policy & Procedure Manual", file: "TX Assisted Living Type A and B PP Manual.docx" },
  "va-alf": { title: "Virginia Assisted Living Facility (ALF) Policy & Procedure Manual", file: "VA Assisted Living Facility (ALF) PP Manual.docx" },
  "wi-cbrf": { title: "Wisconsin Community-Based Residential Facility (CBRF) Policy & Procedure Manual", file: "WI Community-Based Residential Facility (CBRF) PP Manual.docx" },
  "wi-afh": { title: "Wisconsin Licensed Adult Family Home (AFH 3-4 Bed) Policy & Procedure Manual", file: "WI Licensed Adult Family Home (AFH 3-4 Bed) PP Manual.docx" },
  "wi-rcac": { title: "Wisconsin Residential Care Apartment Complex (RCAC) Policy & Procedure Manual", file: "WI Residential Care Apartment Complex (RCAC) PP Manual.docx" },
  "wi-home-care": { title: "Wisconsin In-Home Care Agency Policy & Procedure Manual", file: "WI_Home_Care_PP_Manual.docx" },
  "wi-open-home-care": { title: "How to Open an In-Home Care Agency in Wisconsin", file: "How_to_Open_an_In_Home_Care_Agency_in_Wisconsin.pdf" },
  "wi-home-care-handbook": { title: "Wisconsin In-Home Care Caregiver Handbook", file: "WI_Home_Care_Caregiver_Handbook.docx" },
  "wi-home-care-forms": { title: "Wisconsin In-Home Care Agency Forms Packet", file: "WI_Home_Care_Forms_Packet.docx" },
  "wi-referral-system": { title: "The Referral System \u2014 Wisconsin Edition", file: "The_Referral_System_Wisconsin_Edition.docx" },

  // ===== Employee Handbook line =====
  "ar-al-handbook": { title: "Arkansas Assisted Living Employee Handbook", file: "AR Assisted Living Employee Handbook.docx" },
  "az-al-handbook": { title: "Arizona Assisted Living Employee Handbook", file: "AZ Assisted Living Employee Handbook.docx" },
  "ca-rcfe-handbook": { title: "California RCFE Employee Handbook", file: "CA RCFE Employee Handbook.docx" },
  "co-al-handbook": { title: "Colorado Assisted Living Employee Handbook", file: "CO Assisted Living Employee Handbook.docx" },
  "fl-al-handbook": { title: "Florida Assisted Living Employee Handbook", file: "FL Assisted Living Employee Handbook.docx" },
  "ga-al-handbook": { title: "Georgia Assisted Living Employee Handbook", file: "GA Assisted Living Employee Handbook.docx" },
  "nm-al-handbook": { title: "New Mexico Assisted Living Employee Handbook", file: "NM Assisted Living Employee Handbook.docx" },
  "oh-rcf-handbook": { title: "Ohio Residential Care Facility Employee Handbook", file: "OH Residential Care Facility Employee Handbook.docx" },
  "sc-crcf-handbook": { title: "South Carolina Community Residential Care Facility Employee Handbook", file: "SC Community Residential Care Facility Employee Handbook.docx" },
  "tn-aclf-handbook": { title: "Tennessee Assisted-Care Living Facility Employee Handbook", file: "TN Assisted-Care Living Facility Employee Handbook.docx" },
  "tx-al-handbook": { title: "Texas Assisted Living Employee Handbook", file: "TX Assisted Living Employee Handbook.docx" },
  "va-al-handbook": { title: "Virginia Assisted Living Employee Handbook", file: "VA Assisted Living Employee Handbook.docx" },
  "wi-cbrf-handbook": { title: "Wisconsin Community-Based Residential Facility Employee Handbook", file: "WI Community-Based Residential Facility Employee Handbook.docx" },
  // ===== Care Provider Employee Handbook line =====
  "ar-care-handbook": { title: "Arkansas Care Provider Employee Handbook", file: "AR_Care_Provider_Employee_Handbook.docx" },
  "az-care-handbook": { title: "Arizona Care Provider Employee Handbook", file: "AZ_Care_Provider_Employee_Handbook.docx" },
  "ca-care-handbook": { title: "California Care Provider Employee Handbook", file: "CA_Care_Provider_Employee_Handbook.docx" },
  "co-care-handbook": { title: "Colorado Care Provider Employee Handbook", file: "CO_Care_Provider_Employee_Handbook.docx" },
  "fl-care-handbook": { title: "Florida Care Provider Employee Handbook", file: "FL_Care_Provider_Employee_Handbook.docx" },
  "ga-care-handbook": { title: "Georgia Care Provider Employee Handbook", file: "GA_Care_Provider_Employee_Handbook.docx" },
  "nm-care-handbook": { title: "New Mexico Care Provider Employee Handbook", file: "NM_Care_Provider_Employee_Handbook.docx" },
  "oh-care-handbook": { title: "Ohio Care Provider Employee Handbook", file: "OH_Care_Provider_Employee_Handbook.docx" },
  "oh-home-care": { title: "Ohio In-Home Care Agency Policy & Procedure Manual", file: "OH_Home_Care_PP_Manual.docx" },
  "oh-open-home-care": { title: "How to Open an In-Home Care Agency in Ohio", file: "How_to_Open_an_In_Home_Care_Agency_in_Ohio.pdf" },
  "oh-home-care-handbook": { title: "Caregiver Handbook for an Ohio In-Home Care Agency", file: "OH_Home_Care_Caregiver_Handbook.docx" },
  "oh-home-care-forms": { title: "Forms Packet for an Ohio In-Home Care Agency", file: "OH_Home_Care_Forms_Packet.docx" },
  "oh-referral-system": { title: "The Referral System \u2014 Ohio Edition", file: "The_Referral_System_Ohio_Edition.docx" },
  "sc-care-handbook": { title: "South Carolina Care Provider Employee Handbook", file: "SC_Care_Provider_Employee_Handbook.docx" },
  "tn-care-handbook": { title: "Tennessee Care Provider Employee Handbook", file: "TN_Care_Provider_Employee_Handbook.docx" },
  "tx-care-handbook": { title: "Texas Care Provider Employee Handbook", file: "TX_Care_Provider_Employee_Handbook.docx" },
  "va-care-handbook": { title: "Virginia Care Provider Employee Handbook", file: "VA_Care_Provider_Employee_Handbook.docx" },
  "wi-care-handbook": { title: "Wisconsin Care Provider Employee Handbook", file: "WI_Care_Provider_Employee_Handbook.docx" },

  // ===== Brain Injury Residential line =====
  "co-brain-injury": { title: "Brain Injury Residential Policy & Procedure Manual (Colorado)", file: "CO_Brain_Injury_Residential_PP_Manual.docx" },
  "co-brain-injury-forms": { title: "Brain Injury Residential Forms Packet (Colorado)", file: "CO_Brain_Injury_Residential_Forms_Packet.docx" },
  "co-brain-injury-referral": { title: "The Brain Injury Referral System (Colorado Edition)", file: "The_Brain_Injury_Referral_System_Colorado_Edition.docx" },
  "co-open-brain-injury-home": { title: "How to Open a Brain Injury Residential Home in Colorado", file: "How_to_Open_a_Brain_Injury_Residential_Home_in_Colorado.pdf" },
  "az-brain-injury": { title: "Brain Injury Assisted Living Policy & Procedure Manual (Arizona)", file: "AZ_Brain_Injury_Assisted_Living_PP_Manual.docx" },
  "az-brain-injury-forms": { title: "Brain Injury Assisted Living Forms Packet (Arizona)", file: "AZ_Brain_Injury_Assisted_Living_Forms_Packet.docx" },
  "az-brain-injury-referral": { title: "The Brain Injury Referral System (Arizona Edition)", file: "The_Brain_Injury_Referral_System_Arizona_Edition.docx" },
  "az-open-brain-injury-home": { title: "How to Open an Assisted Living Home for Adults with Brain Injury in Arizona", file: "How_to_Open_an_Assisted_Living_Home_for_Brain_Injury_in_Arizona.pdf" },
  "tx-brain-injury": { title: "Brain Injury Assisted Living Policy & Procedure Manual (Texas)", file: "TX_Brain_Injury_Assisted_Living_PP_Manual.docx" },
  "tx-brain-injury-forms": { title: "Brain Injury Assisted Living Forms Packet (Texas)", file: "TX_Brain_Injury_Assisted_Living_Forms_Packet.docx" },
  "tx-brain-injury-referral": { title: "The Brain Injury Referral System (Texas Edition)", file: "The_Brain_Injury_Referral_System_Texas_Edition.docx" },
  "tx-home-care": { title: "Non-Medical Home Care (PAS) Policy & Procedure Manual (Texas)", file: "TX_Home_Care_PP_Manual.docx" },
  "tx-open-home-care": { title: "How to Open a Non-Medical Home Care Agency in Texas", file: "How_to_Open_a_Non-Medical_Home_Care_Agency_in_Texas.pdf" },
  "tx-home-care-handbook": { title: "Non-Medical Home Care Caregiver Handbook (Texas)", file: "TX_Home_Care_Caregiver_Handbook.docx" },
  "tx-home-care-forms": { title: "Non-Medical Home Care Forms Packet (Texas)", file: "TX_Home_Care_Forms_Packet.docx" },
  "tx-referral-system": { title: "The Referral System (Texas Edition)", file: "The_Referral_System_Texas_Edition.docx" },
  "fl-home-care": { title: "Homemaker & Companion Services Policy & Procedure Manual (Florida)", file: "FL_Home_Care_PP_Manual.docx" },
  "fl-open-home-care": { title: "How to Open a Homemaker & Companion Services Business in Florida", file: "How_to_Open_a_Homemaker_and_Companion_Services_Business_in_Florida.pdf" },
  "fl-home-care-handbook": { title: "Homemaker & Companion Caregiver Handbook (Florida)", file: "FL_Home_Care_Caregiver_Handbook.docx" },
  "fl-home-care-forms": { title: "Homemaker & Companion Services Forms Packet (Florida)", file: "FL_Home_Care_Forms_Packet.docx" },
  "fl-referral-system": { title: "The Referral System (Florida Edition)", file: "The_Referral_System_Florida_Edition.docx" },
  "ga-home-care": { title: "Private Home Care Provider Policy & Procedure Manual (Georgia)", file: "GA_Home_Care_PP_Manual.docx" },
  "ga-open-home-care": { title: "How to Open a Private Home Care Business in Georgia", file: "How_to_Open_a_Private_Home_Care_Business_in_Georgia.pdf" },
  "ga-home-care-handbook": { title: "Private Home Care Caregiver Handbook (Georgia)", file: "GA_Home_Care_Caregiver_Handbook.docx" },
  "ga-home-care-forms": { title: "Private Home Care Provider Forms Packet (Georgia)", file: "GA_Home_Care_Forms_Packet.docx" },
  "ga-referral-system": { title: "The Referral System (Georgia Edition)", file: "The_Referral_System_Georgia_Edition.docx" },
  "co-home-care": { title: "Class B Home Care Agency Policy & Procedure Manual (Colorado)", file: "CO_Home_Care_PP_Manual.docx" },
  "co-open-home-care": { title: "How to Open a Home Care Agency in Colorado", file: "How_to_Open_a_Home_Care_Agency_in_Colorado.pdf" },
  "co-home-care-handbook": { title: "Home Care Caregiver Handbook (Colorado)", file: "CO_Home_Care_Caregiver_Handbook.docx" },
  "co-home-care-forms": { title: "Class B Home Care Agency Forms Packet (Colorado)", file: "CO_Home_Care_Forms_Packet.docx" },
  "co-referral-system": { title: "The Referral System (Colorado Edition)", file: "The_Referral_System_Colorado_Edition.docx" },
  "nm-home-care": { title: "New Mexico Home Health Agency Policy & Procedure Manual", file: "NM_Home_Health_Agency_PP_Manual.docx" },
  "nm-open-home-care": { title: "How to Open a Home Health Agency in New Mexico", file: "How_to_Open_a_Home_Health_Agency_in_New_Mexico.pdf" },
  "nm-home-care-handbook": { title: "Home Health Caregiver Handbook (New Mexico)", file: "NM_Home_Health_Caregiver_Handbook.docx" },
  "nm-home-care-forms": { title: "New Mexico Home Health Agency Forms Packet", file: "NM_Home_Health_Agency_Forms_Packet.docx" },
  "nm-referral-system": { title: "The Referral System (New Mexico Edition)", file: "The_Referral_System_New_Mexico_Edition.docx" },
  "nc-home-care": { title: "Home Care Agency Policy & Procedure Manual (North Carolina)", file: "NC_Home_Care_PP_Manual.docx" },
  "nc-open-home-care": { title: "How to Open a Home Care Agency in North Carolina", file: "How_to_Open_a_Home_Care_Agency_in_North_Carolina.pdf" },
  "nc-home-care-handbook": { title: "Home Care Caregiver Handbook (North Carolina)", file: "NC_Home_Care_Caregiver_Handbook.docx" },
  "nc-home-care-forms": { title: "Home Care Agency Forms Packet (North Carolina)", file: "NC_Home_Care_Forms_Packet.docx" },
  "nc-referral-system": { title: "The Referral System (North Carolina Edition)", file: "The_Referral_System_North_Carolina_Edition.docx" },
  "ny-home-care": { title: "Licensed Home Care Services Agency (LHCSA) Policy & Procedure Manual (New York)", file: "NY_LHCSA_PP_Manual.docx" },
  "ny-open-home-care": { title: "How to Open a Home Care Agency in New York", file: "How_to_Open_a_Home_Care_Agency_in_New_York.pdf" },
  "ny-home-care-handbook": { title: "Caregiver Handbook for a New York LHCSA", file: "NY_LHCSA_Caregiver_Handbook.docx" },
  "ny-home-care-forms": { title: "Forms Packet for a New York LHCSA", file: "NY_LHCSA_Forms_Packet.docx" },
  "ny-referral-system": { title: "The Referral System (New York Edition)", file: "The_Referral_System_New_York_Edition.docx" },
  "sc-home-care": { title: "Policy & Procedure Manual for a South Carolina In-Home Care Provider (IHCP)", file: "SC_Home_Care_PP_Manual.docx" },
  "sc-open-home-care": { title: "How to Open a Home Care Agency in South Carolina", file: "How_to_Open_a_Home_Care_Agency_in_South_Carolina.pdf" },
  "sc-home-care-handbook": { title: "Caregiver Handbook for a South Carolina In-Home Care Provider", file: "SC_Home_Care_Caregiver_Handbook.docx" },
  "sc-home-care-forms": { title: "Forms Packet for a South Carolina In-Home Care Provider", file: "SC_Home_Care_Forms_Packet.docx" },
  "sc-referral-system": { title: "The Referral System (South Carolina Edition)", file: "The_Referral_System_South_Carolina_Edition.docx" },
  "tx-open-brain-injury-home": { title: "How to Open an Assisted Living Home for Adults with Brain Injury in Texas", file: "How_to_Open_an_Assisted_Living_Home_for_Brain_Injury_in_Texas.pdf" },
  "fl-brain-injury": { title: "Brain Injury Transitional Living Facility Policy & Procedure Manual (Florida)", file: "FL_Brain_Injury_TLF_PP_Manual.docx" },
  "fl-brain-injury-forms": { title: "Brain Injury Transitional Living Facility Forms Packet (Florida)", file: "FL_Brain_Injury_TLF_Forms_Packet.docx" },
  "fl-brain-injury-referral": { title: "The Brain Injury Referral System (Florida Edition)", file: "The_Brain_Injury_Referral_System_Florida_Edition.docx" },
  "fl-open-brain-injury-home": { title: "How to Open a Brain Injury Transitional Living Facility in Florida", file: "How_to_Open_a_Brain_Injury_Transitional_Living_Facility_in_Florida.pdf" },
  "ga-brain-injury": { title: "Brain Injury Personal Care Home Policy & Procedure Manual (Georgia)", file: "GA_Brain_Injury_PCH_PP_Manual.docx" },
  "ga-brain-injury-forms": { title: "Brain Injury Personal Care Home Forms Packet (Georgia)", file: "GA_Brain_Injury_PCH_Forms_Packet.docx" },
  "ga-brain-injury-referral": { title: "The Brain Injury Referral System (Georgia Edition)", file: "The_Brain_Injury_Referral_System_Georgia_Edition.docx" },
  "ga-open-brain-injury-home": { title: "How to Open a Brain Injury Personal Care Home in Georgia", file: "How_to_Open_a_Brain_Injury_Personal_Care_Home_in_Georgia.pdf" },
  "oh-brain-injury": { title: "Brain Injury Residential Care Facility Policy & Procedure Manual (Ohio)", file: "OH_Brain_Injury_RCF_PP_Manual.docx" },
  "oh-brain-injury-forms": { title: "Brain Injury Residential Care Facility Forms Packet (Ohio)", file: "OH_Brain_Injury_RCF_Forms_Packet.docx" },
  "oh-brain-injury-referral": { title: "The Brain Injury Referral System (Ohio Edition)", file: "The_Brain_Injury_Referral_System_Ohio_Edition.docx" },
  "oh-open-brain-injury-home": { title: "How to Open a Brain Injury Residential Care Facility in Ohio", file: "How_to_Open_a_Brain_Injury_Residential_Care_Facility_in_Ohio.pdf" },
  "ca-brain-injury": { title: "Brain Injury Adult Residential Facility Policy & Procedure Manual (California)", file: "CA_Brain_Injury_ARF_PP_Manual.docx" },
  "ca-brain-injury-forms": { title: "Brain Injury Adult Residential Facility Forms Packet (California)", file: "CA_Brain_Injury_ARF_Forms_Packet.docx" },
  "ca-brain-injury-referral": { title: "The Brain Injury Referral System (California Edition)", file: "The_Brain_Injury_Referral_System_California_Edition.docx" },
  "ca-open-brain-injury-home": { title: "How to Open a Brain Injury Adult Residential Facility in California", file: "How_to_Open_a_Brain_Injury_Adult_Residential_Facility_in_California.pdf" },
  "ca-home-care": { title: "Non-Medical Home Care Policy & Procedure Manual (California)", file: "CA_Home_Care_PP_Manual.docx" },
  "ca-open-home-care": { title: "How to Open a Non-Medical Home Care Agency in California", file: "How_to_Open_a_Non-Medical_Home_Care_Agency_in_California.pdf" },
  "ca-home-care-handbook": { title: "Non-Medical Home Care Caregiver Handbook (California)", file: "CA_Home_Care_Caregiver_Handbook.docx" },
  "ca-home-care-forms": { title: "Non-Medical Home Care Forms Packet (California)", file: "CA_Home_Care_Forms_Packet.docx" },
  "ca-referral-system": { title: "The Referral System (California Edition)", file: "The_Referral_System_California_Edition.docx" },

  // ===== How-To / Business Startup Guides =====
  "co-open-host-home": { title: "How to Open a Host Home Business in Colorado", file: "How_to_Open_a_Host_Home_Business_in_Colorado.pdf" },
  "az-open-dev-home": { title: "How to Open a Developmental Home Business in Arizona", file: "How_to_Open_a_Developmental_Home_Business_in_Arizona.pdf" },
  "tx-open-host-home": { title: "How to Open a Host Home Business in Texas", file: "How_to_Open_a_Host_Home_Business_in_Texas.pdf" },
  "fl-open-group-home": { title: "How to Open a Group Home Business in Florida", file: "How_to_Open_a_Group_Home_Business_in_Florida.pdf" },
  "oh-open-shared-living": { title: "How to Open a Shared Living (Host Home) Business in Ohio", file: "How_to_Open_a_Shared_Living_Business_in_Ohio.pdf" },
  "ca-open-group-home": { title: "How to Open a Group Home Business in California", file: "How_to_Open_a_Group_Home_Business_in_California.pdf" },
  "ga-open-group-home": { title: "How to Open a Group Home Business in Georgia", file: "How_to_Open_a_Group_Home_Business_in_Georgia.pdf" },
  "nm-open-group-home": { title: "How to Open a Group Home Business in New Mexico", file: "How_to_Open_a_Group_Home_Business_in_New_Mexico.pdf" },
  "tn-open-group-home": { title: "How to Open a Group Home Business in Tennessee", file: "How_to_Open_a_Group_Home_Business_in_Tennessee.pdf" },
  "sc-open-group-home": { title: "How to Open a Group Home Business in South Carolina", file: "How_to_Open_a_Group_Home_Business_in_South_Carolina.pdf" },
  "wi-open-group-home": { title: "How to Open a Group Home Business in Wisconsin", file: "How_to_Open_a_Group_Home_Business_in_Wisconsin.pdf" },
  "va-open-group-home": { title: "How to Open a Group Home Business in Virginia", file: "How_to_Open_a_Group_Home_Business_in_Virginia.pdf" },
  "ar-open-group-home": { title: "How to Open a Group Home Business in Arkansas", file: "How_to_Open_a_Group_Home_Business_in_Arkansas.pdf" },
  // ===== Arizona Non-Medical Home Care line (no state license) =====
  "az-home-care": { title: "Arizona Non-Medical Home Care Policy & Procedure Manual", file: "AZ_Home_Care_PP_Manual.docx" },
  "az-open-home-care": { title: "How to Open a Non-Medical Home Care Agency in Arizona", file: "How_to_Open_a_Home_Care_Agency_in_Arizona.pdf" },
  "az-home-care-handbook": { title: "Arizona Non-Medical Home Care Caregiver Handbook", file: "AZ_Home_Care_Caregiver_Handbook.docx" },
  "az-home-care-forms": { title: "Arizona Non-Medical Home Care Forms Packet", file: "AZ_Home_Care_Forms_Packet.docx" },
  "az-referral-system": { title: "The Referral System \u2014 Arizona Edition", file: "The_Referral_System_Arizona_Edition.docx" },
  "az-open-bhrf": { title: "How to Open a Behavioral Health Residential Facility (BHRF) in Arizona", file: "How_to_Open_a_Behavioral_Health_Residential_Facility_in_Arizona.pdf" },
  "az-open-otc": { title: "How to Open an Outpatient Treatment Center (OTC) in Arizona", file: "How_to_Open_an_Outpatient_Treatment_Center_in_Arizona.pdf" },
  // ===== Oregon =====
  "or-home-care": { title: "Oregon In-Home Care Agency Policy & Procedure Manual", file: "OR_Home_Care_PP_Manual.docx" },
  "or-residential-care": { title: "Oregon Residential Care & Assisted Living Policy & Procedure Manual", file: "OR_RCF_ALF_PP_Manual.docx" },
  "or-open-residential-care": { title: "How to Open a Residential Care or Assisted Living Facility in Oregon", file: "How_to_Open_a_Residential_Care_or_Assisted_Living_Facility_in_Oregon.pdf" },
  "or-residential-care-handbook": { title: "Oregon Residential Care & Assisted Living Caregiver Handbook", file: "OR_RCF_ALF_Caregiver_Handbook.docx" },
  "or-residential-care-forms": { title: "Oregon Residential Care & Assisted Living Forms Packet", file: "OR_RCF_ALF_Forms_Packet.docx" },
  "or-open-home-care": { title: "How to Open an In-Home Care Agency in Oregon", file: "How_to_Open_an_In_Home_Care_Agency_in_Oregon.pdf" },
  "or-home-care-handbook": { title: "Caregiver Handbook for an Oregon In-Home Care Agency", file: "OR_Home_Care_Caregiver_Handbook.docx" },
  "or-home-care-forms": { title: "Forms Packet for an Oregon In-Home Care Agency", file: "OR_Home_Care_Forms_Packet.docx" },
  "or-referral-system": { title: "The Referral System \u2014 Oregon Edition", file: "The_Referral_System_Oregon_Edition.docx" },
  "or-sud": { title: "Oregon Outpatient Substance Use Disorder Treatment Policy & Procedure Manual", file: "OR_Outpatient_SUD_PP_Manual.docx" },
  "or-mh": { title: "Oregon Outpatient Community Mental Health Policy & Procedure Manual", file: "OR_Outpatient_MH_PP_Manual.docx" },
  "nj-open-group-home": { title: "How to Open a Group Home in New Jersey", file: "How_to_Open_a_Group_Home_in_New_Jersey.pdf" },
  "nj-group-home": { title: "New Jersey Community Residence (Group Home) Policy & Procedure Manual", file: "NJ_Group_Home_PP_Manual.docx" },
  "nj-group-home-handbook": { title: "New Jersey Community Residence (Group Home) Direct Support Professional Handbook", file: "NJ_Group_Home_Caregiver_Handbook.docx" },
  "nj-group-home-forms": { title: "New Jersey Community Residence (Group Home) Forms Packet", file: "NJ_Group_Home_Forms_Packet.docx" },
  // ===== Behavioral Health \u2014 New York =====
  "ny-sud": { title: "Substance Use Disorder Services Policy & Procedure Manual (New York)", file: "NY_SUD_PP_Manual.docx" },
  "ny-mh": { title: "Mental Health Services Policy & Procedure Manual (New York)", file: "NY_MH_PP_Manual.docx" },
  "ny-sud-referral": { title: "The Substance Use Referral System (New York Edition)", file: "The_Substance_Use_Referral_System_New_York_Edition.docx" },
  "ny-mh-referral": { title: "The Mental Health Referral System (New York Edition)", file: "The_Mental_Health_Referral_System_New_York_Edition.docx" },
  // ===== Behavioral Health \u2014 North Carolina =====
  "nc-sud": { title: "Substance Use Disorder Services Policy & Procedure Manual (North Carolina)", file: "NC_SUD_PP_Manual.docx" },
  "nc-mh": { title: "Mental Health Services Policy & Procedure Manual (North Carolina)", file: "NC_MH_PP_Manual.docx" },
  "nc-sud-referral": { title: "The Substance Use Referral System (North Carolina Edition)", file: "The_Substance_Use_Referral_System_North_Carolina_Edition.docx" },
  "nc-mh-referral": { title: "The Mental Health Referral System (North Carolina Edition)", file: "The_Mental_Health_Referral_System_North_Carolina_Edition.docx" },
  // ===== Home Care \u2014 New Jersey (Health Care Service Firm) =====
  "nj-home-care": { title: "Home Care Policy & Procedure Manual (New Jersey)", file: "NJ_Home_Care_HCSF_PP_Manual.docx" },
  "nj-open-home-care": { title: "How to Open a Home Care Agency in New Jersey", file: "How_to_Open_a_Home_Care_Agency_in_New_Jersey.pdf" },
  "nj-home-care-handbook": { title: "Home Health Aide Caregiver Handbook (New Jersey)", file: "Home_Health_Aide_Caregiver_Handbook_New_Jersey.docx" },
  "nj-home-care-forms": { title: "Home Care Agency Forms Packet (New Jersey)", file: "Home_Care_Agency_Forms_Packet_New_Jersey.docx" },
  "nj-sud": { title: "Substance Use Disorder Services Policy & Procedure Manual", file: "NJ_SUD_PP_Manual.docx" },
  "nj-mh": { title: "Mental Health Services Policy & Procedure Manual", file: "NJ_MH_PP_Manual.docx" },
  "nj-sud-referral": { title: "The Substance Use Referral System \u2014 New Jersey Edition", file: "The_Substance_Use_Referral_System_New_Jersey_Edition.docx" },
  "nj-mh-referral": { title: "The Mental Health Referral System \u2014 New Jersey Edition", file: "The_Mental_Health_Referral_System_New_Jersey_Edition.docx" },
  // ===== Assisted Living \u2014 North Carolina, New York, New Jersey =====
  "nc-adult-care-home": { title: "Adult Care Home Policy & Procedure Manual (North Carolina)", file: "Adult_Care_Home_Policy_Manual_North_Carolina.docx" },
  "nc-open-adult-care-home": { title: "How to Open an Adult Care Home in North Carolina", file: "How_to_Open_an_Adult_Care_Home_in_North_Carolina.pdf" },
  "nc-adult-care-home-forms": { title: "Adult Care Home Forms Packet (North Carolina)", file: "Adult_Care_Home_Forms_Packet_North_Carolina.docx" },
  "ny-adult-care-facility": { title: "Adult Care Facility & Assisted Living Residence Policy & Procedure Manual (New York)", file: "Adult_Care_Facility_ALR_Policy_Manual_New_York.docx" },
  "ny-open-adult-care-facility": { title: "How to Open an Adult Care Facility in New York", file: "How_to_Open_an_Adult_Care_Facility_in_New_York.pdf" },
  "ny-adult-care-facility-forms": { title: "Adult Care Facility & Assisted Living Residence Forms Packet (New York)", file: "Adult_Care_Facility_Forms_Packet_New_York.docx" },
  "nj-assisted-living": { title: "Assisted Living Residence & Comprehensive Personal Care Home Policy & Procedure Manual (New Jersey)", file: "Assisted_Living_CPCH_Policy_Manual_New_Jersey.docx" },
  "nj-open-assisted-living": { title: "How to Open an Assisted Living Residence in New Jersey", file: "How_to_Open_an_Assisted_Living_Residence_in_New_Jersey.pdf" },
  "nj-assisted-living-forms": { title: "Assisted Living Residence & Comprehensive Personal Care Home Forms Packet (New Jersey)", file: "Assisted_Living_CPCH_Forms_Packet_New_Jersey.docx" },
};

function getProduct(slug) {
  if (!slug || typeof slug !== "string") return null;
  return PRODUCTS[slug] || null;
}

module.exports = { PRODUCTS, PRICE_CENTS, MANUAL_PRICE_CENTS, CURRENCY, getProduct, priceForSlug };
